### ISSUE TITLE
CHAOSScon19EU: remove CFP from page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#102]
@klumb please remove the CFP block from the CHAOSScon19EU page.

**Comment by jgbarah** [comment]
Wouldn't it be better to keep it, with a clear notice at the top stating "the CFP is already closed". That way, it would still be there for future reference...

**Comment by GeorgLink** [comment]
People will care more about the Schedule from now on. How about moving the
module to the bottom? That keeps the information available.

**Comment by jgbarah** [comment]
That's a good idea!

**Comment by GeorgLink** [comment]
@klumb It would be great if you could move the DFP module to the bottom of the CHAOSScon page soon.

**Comment by klumb** [comment]
Okay, moving now.
