### ISSUE TITLE
Rename participate files for 3 blocks.

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/website#106]
With the new PR #105 I've left all of the file names as is to avoid breaking the website on the backend :) We should eventually rename these to make more sense. I propose:

chaoss-community-call.md -> common-metrics-wg.md

growth-maturity-decline-weekly-call.md -> growth-maturity-decline-wg.md

diversity-inclusion-workgroup-weekly-call.md -> diversity-inclusion-wg.md

**Comment by klumb** [comment]
I agree. Assigned it to myself.

**Comment by geekygirldawn** [comment]
It looks like this is completed.
