### ISSUE TITLE
Add blog post to website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#109]
Blog post was already merged #107

**Comment by klumb** [comment]
@GeorgLink , @jgbarah , and @sgoggins 
I created the blog post. Please review:
https://chaoss.community/news/2019/01/30/contributing-to-the-gmd-work-group/

We are pulling blog posts directly from the github markdown file now so if you edit the original markdown file it will change on the website as well.

**Comment by GeorgLink** [comment]
Thank you Kevin.

@jgbarah and @sgoggins: The blog post does not have a by-line. Do you want one?

**Comment by jgbarah** [comment]
> The blog post does not have a by-line. Do you want one?

I find it ok as it is, thanks ;-)

I was reviewing it, I found no error. Thanks! From my side, we can close this issue.
