### ISSUE TITLE
Published Work Section (Research)

### ISSUE THREAD

**Issue by klumb** [chaoss/website#11]
This issue is for discussion of a research publication page.

**Comment by klumb** [comment]
This would under the About menu.

**Comment by mpgjon** [comment]
For the markdown file in this section; are there any already-published works or related research or other assets we'd like to include?  If so, if I can be directed to them I can start pulling together a markdown file with actual *stuff* in it.

**Comment by GeorgLink** [comment]
I have been adding everything to the bottom of the media page: https://chaoss.community/media/

@klumb do you think we need a separate publications section?

**Comment by klumb** [comment]
@mpgjon and @klumb,

It is not obvious to me that publications would be on the media page. I think it is more closely related to the blog and community page. Perhaps this is part of the larger conversation about the Community navigation label and the sub-pages/navigation that could exist there. A dedicated page might be nice there.

**Comment by tharun143** [comment]
@klumb @GeorgLink I would like to work on this issue this may be useful for understanding about the work done by CHAOSS and also I would like to apply for google season of docs. Maybe this experience would be helpful at the time of participating and this would also improve my knowledge about the community idk whether I would be selected for the season of docs or not but still giving a try. 

I think we should have publications in the community section bcoz at the time of exploring website I saw the publications in the media section and got confused. I thought I should open an issue regarding this but I found there is an already issue opened on this.

**Comment by tharun143** [comment]
@klumb Is there anything I could do with this issue. I understood that you need a md file.

**Comment by klumb** [comment]
The more I think about this, the more it makes sense to leave it on the media page.

I would propose adding two new sections to the page though. One section that has a brief bio/mission statement for CHAOSS and one section that lists research publications. @GeorgLink @tharun143 - Thoughts?

**Comment by klumb** [comment]
Update past events at the bottom of this page.

**Comment by tharun143** [comment]
@klumb I think media means in general people will think about your social media activities or anything about CHAOSS community released like a photo album, video.

The media page is completely combined like you have the material section, contact section and at the same time, you have publications and again including bio/ mission of CHAOSS makes it combined page. 

I think it's better to have publications in the community section where you can include publications and blogs.

This is just my thought.

**Comment by klumb** [comment]
A Media page, sometimes called a Press or News page, a Press Kit, or a Media Kit is a page of your website designed as a specific marketing tool for those people who want to learn more about you, but also (and especially) those who want to write about you. This is an external-facing page.

Here is a reference;
https://www.outboxonline.com/your-websites-media-page-what-to-include/

Social media, community pages, photo albums, and blogs have different purposes. They are about building and promoting community internally.

**Comment by tharun143** [comment]
@klumb Oh, the reference is good and you are following the same pattern. Sorry for my misunderstanding I apologize. So we need to include publications in the media section.

**Comment by klumb** [comment]
Add research to navigation

**Comment by klumb** [comment]
Archiving
