### ISSUE TITLE
Unify language to "Working Group"

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#111]
We discussed during this weeks call that we want to uniformly use "Working Group". 
For this, we need to replace "workgroup" and "work group".

* https://chaoss.community/metrics/
* https://chaoss.community/news/2019/01/30/contributing-to-the-gmd-work-group/

**Comment by GeorgLink** [comment]
I fixed all the markdown references. The two links above need wordpess access to change.

**Comment by klumb** [comment]
Done.
I am closing the issue.
