### ISSUE TITLE
Community sub-pages: "Blog" and "Events" ?

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#113]
This is for the idea to add two new sub-menu items to Community: "Blog" and "Events" 

The "Blog" page would be like the community page but without the top items.

The "Events" page would consists of three sections:

1. Block with content from /CHAOSScon/past-future.md
2. Block with content from /Community/conferences.md
3. Block with content from /Community/Events/past-events.md

**Comment by GeorgLink** [comment]
I would move /Community/conferences.md to the Events place and rename it to `upcoming-events.md`

**Comment by klumb** [comment]
Good idea

**Comment by klumb** [comment]
Hold off an re-evaluate after restructure #140 #142 #145 #146

**Comment by klumb** [comment]
This has been resolved
