### ISSUE TITLE
remove CHAOSScon advertisement from homepage

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#116]
Our homepage has a gigantic advertisement for the last CHAOSScon. I think we can hide the button until we are ready for the next conference.

![image](https://user-images.githubusercontent.com/8862021/53137643-1b650200-3549-11e9-9a5f-a54734b49b09.png)

**Comment by germonprez** [comment]
Maybe replace it with "Join a Working Group"

**Comment by klumb** [comment]
I have replaced it with "Join a Working Group"

**Comment by GeorgLink** [comment]
Awesome, thanks!
