### ISSUE TITLE
Improve email list descriptions on /participate page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#118]
* "Join Mailing List" needs to include D&I list
* Add a description for each mailing list
* Join "How to participate" and "Join Mailing List" sections

**Comment by klumb** [comment]
I think we should move the archive links to where the Wiki is now located on the page.

**Comment by klumb** [comment]
would resolve #112

**Comment by GeorgLink** [comment]
+1 good idea!

**Comment by klumb** [comment]
The modules have been moved. need to make some edits to the markdown folders.

**Comment by klumb** [comment]
Think we should have the mailing list info in the top module and archive lists in the bottom module - rename header to email archives.

**Comment by klumb** [comment]
Changes made
