### ISSUE TITLE
Bug in Wordpress Rendering on md links on participate page

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/website#123]
There seems to be an issue with the way that wordpress is rendering the md link to the agenda in website/Participate/diversity-inclusion-workgroup-weekly-call.md If you look at the [md page in GitHub](https://github.com/chaoss/website/blob/master/Participate/diversity-inclusion-workgroup-weekly-call.md), the link looks fine. I'm going to submit a PR in a few minutes to add the agenda link to the common metrics wg section on the participate page, since I'm guessing it will have the same issue.

**Comment by geekygirldawn** [comment]
While you're fixing this issue might be a good time to also fix issue #106 since it deals with the same files :)

**Comment by klumb** [comment]
@geekygirldawn I am looking into this

**Comment by klumb** [comment]
This was just a minor error in the markdown, I fixed it.
