### ISSUE TITLE
Add: About/FAQ

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#13]
Copy FAQ from Whitepaper and add more. Ideally let them live in the repository.

https://github.com/chaoss/whitepaper/blob/master/whitepaper.md#6-faq

**Comment by klumb** [comment]
Location? new page?  In navigation or link from metrics page?

**Comment by GeorgLink** [comment]
Add FAQ under ABOUT ???

**Comment by bhavayAnand9** [comment]
If no one is assigned this issue can I work on it?

**Comment by klumb** [comment]
@bhavayAnand9,  Yes you can work on this. Please create it as a markdown file. Let me know if you have any questions.  @GeorgLink, any thoughts?

**Comment by GeorgLink** [comment]
👍 Thanks @bhavayAnand9 for the initiative!

**Comment by klumb** [comment]
Thanks @bhavayAnand9 

To implement #92 , the page needs to be created on the word press site. Assigning to myself.

**Comment by GeorgLink** [comment]
The WG README's are serving this purpose.
