### ISSUE TITLE
404 Errors in https://chaoss.community/metrics/

### ISSUE THREAD

**Issue by s-ankur** [chaoss/website#131]
> Goals and Questions related to Growth-Maturity-Decline are located at (https://github.com/chaoss/metrics/blob/master/2_Growth-Maturity-Decline.md)

> Goals and Questions related to Diversity and Inclusion are located at (https://github.com/chaoss/metrics/blob/master/1_Diversity-Inclusion.md)
<br>
These files do not exist.

**Comment by klumb** [comment]
Thanks ankur.
Could you to tell us where you found them.

**Comment by GeorgLink** [comment]
Sounds like metrics links.

https://chaoss.community/metrics/

I think we can remove the links from the working group blob.

**Comment by s-ankur** [comment]
Yes this solves it.
