### ISSUE TITLE
Remove Prospector from Software Page

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#139]
As Prospector was marked as inactive at the March 2019 board meeting, I believe it should be removed from the website.

**Comment by GeorgLink** [comment]
Marked as `good first issue`. 

This issue requires two steps:

1) create a pull request that removes file /Software/prospector.md
2) @klumb needs to remove the prospector section from the website.

**Comment by klumb** [comment]
@GeorgLink - The prospector section is removed from the website. 

We still need to delete the /Software/prospector.md from the repository.

**Comment by GeorgLink** [comment]
> We still need to delete the /Software/prospector.md from the repository.

That's a good first issue 👍

**Comment by mpgjon** [comment]
Completed with https://github.com/chaoss/website/pull/183 :)

**Comment by klumb** [comment]
thanks @mpgjon
