### ISSUE TITLE
Augur Information and image

### ISSUE THREAD

**Issue by klumb** [chaoss/website#144]
@sgoggins, the Augur information on the website is out of date. 

Software/augur.md file needs to be updated and need a current image

**Comment by bistaastha** [comment]
Hi @klumb ! Can I work on this?

**Comment by klumb** [comment]
Thank you @bistaastha, let me know if you need anything.

**Comment by klumb** [comment]
On the website, this information is displayed at

https://chaoss.community/software/

**Comment by klumb** [comment]
At some point, we will give each piece of software its own page so feel free to provide as much information you deem necessary.

If you would like to design a whole page you may however it is not required for this issue.

**Comment by bistaastha** [comment]
Thanks, I'm working on it :) 

I just looked around this repository to find the image source file. It doesn't seem to be here

**Comment by klumb** [comment]
@bistaastha I cc'd you on an email to @sgoggins to get the image

**Comment by bistaastha** [comment]
> @bistaastha I cc'd you on an email to @sgoggins to get the image

Hi @klumb ! This is great.

However, I had a different concern. The file [Software/augur.md](https://github.com/chaoss/website/blob/master/Software/augur.md) contains the content which needs to be updated, but the image file cannot be updated from the markdown file. I'm also not able to find the current image source file in this repository.

**Comment by klumb** [comment]
Sorry for the confusion @bistaastha.

The website is hosted on Wordpress. Originally all of the content was created and stored there as well.  We have slowly been replacing the WordPress content with the content on GitHub. The image and file do not exist in GitHub because we haven't created them yet. That would be part of this task.  I am happy to chat on Monday if you have questions.

**Comment by klumb** [comment]
@bistaastha I uploaded the Augur image to the software folder.
