### ISSUE TITLE
update WG info on /participate and /metric page in WordPress

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#145]
@klumb 

#143 added Value WG call info. This needs to be reflected in a module on the /participate page.
#143 added a description of the Value WG, which seems to have been intended for the /metric page. Since we are clearing the /metric page for when we release metrics (#140), this info should go somewhere else (see #142).

- [ ] update /participate page modules
    - [ ] new module for Value WG
    - [ ] new module for Risk WG
    - [ ] remove risk from GMD page
- [ ] address #142 to give every WG a page on the website

**Comment by klumb** [comment]
done
