### ISSUE TITLE
Lack of a favicon for the website

### ISSUE THREAD

**Issue by Polaris000** [chaoss/website#163]
The favicon for the website seems to be missing. I think it would be a good idea to have one. 
If not, this issue can be closed. 
Please have a look @GeorgLink @klumb

**Comment by GeorgLink** [comment]
I noticed too, that we don't have a favicon.
I will add a "good-first-issue" to this:
- We need someone to design a favicon. In the "material" section on following page is information about our logo: https://chaoss.community/media/

**Comment by Polaris000** [comment]
Thanks for the response!

**Comment by klumb** [comment]
We don't have access to this on our end. We will need to reach out to the Linux Foundation.

**Comment by mpgjon** [comment]
I cropped up an image for use, given it's a Wordpress install, will need to be granted access to update the favicon in the or have someone drop the image into: Administration Screen > Appearance > Customize. 
![Chaoss favicon](https://user-images.githubusercontent.com/19333663/59933877-1df43d00-93ff-11e9-8124-2bb5d8f16b36.png)

**Comment by klumb** [comment]
Excellent, I will reach out to the Linux Foundation to have them add to the site.

**Comment by mpgjon** [comment]
Following up from our call this morning, see if this one with a transparent BG is a bit better for the favicon.  

![chaos_icon_transparent_50x50](https://user-images.githubusercontent.com/19333663/60138530-917bae80-975f-11e9-8cd6-7d48ca5a0ed3.png)

**Comment by germonprez** [comment]
Thanks @mpgjon

**Comment by klumb** [comment]
Thanks, @mpgjon - the transparent favicon is now live. I am closing this issue.

**Comment by klumb** [comment]
Also thanks @germonprez for moving this to the foundation.
