### ISSUE TITLE
Create CHAOSSconNA'19 and CHAOSSconEU'20 webpages

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#164]
The files already exist in the repository. This issue is about creating and publishing the website.
https://github.com/chaoss/website/tree/master/CHAOSScon

- [x] CHAOSSconNA'19
- [x] CHAOSSconEU'20

**Comment by klumb** [comment]
@GeorgLink These pages are now created. Please open a separate issue to add them to the navigation when you are ready.

https://chaoss.community/chaosscon-2019-na/
https://chaoss.community/chaosscon-2020-eu/

**Comment by GeorgLink** [comment]
Thank you!
