### ISSUE TITLE
Add link to CommunityBridge on website 

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#169]
I don't know where, but we might want to add a link to CommunityBridge on our website...

Maybe a call to action on multiple pages that we want funding!
Later, maybe a call to action that we are seeking mentees (after we have funding)

Link:
https://funding.communitybridge.org/projects/a4a43b66-f707-47b4-97cc-484285c274a8

Help wanted: Identify where on the website we can place call to actions for funding.

**Comment by mpgjon** [comment]
Hi Georg, I can take this one on.  I think we should put a "Donate" menu item in the main menu that persists across the site.  I don't see that code in the repo though, and assume that config lies in the menu code in the Wordpress install. LMK if that seems like a reasonable location and choice, and if you want me to make the change, feel free to invite me to the WP installation.

**Comment by klumb** [comment]
@mpgjon, I like the idea of adding it to the main navigation menu. I think we need to create a page as well. We can link to community bridge from the page.

**Comment by mpgjon** [comment]
Would you want to link the Donate top-level item to a donate page (and try to embed if we can any of the neat transparency data from CommunityBridge) or directly from Donate to the project URL page on CommunityBridge?  Either way is doable with the former being a bit simpler.

**Comment by klumb** [comment]
For the time being, the former should be sufficient but let's continue talking about this and maybe build some markdown that we can add to other pages or create a dedicated page.

I added it to the main navigation.

**Comment by mpgjon** [comment]
NICE! DO we want to keep this issue open for further discussion; or close this one and create a new one to "Create markdown for use in a CommunityBridge donation block or page"?

**Comment by klumb** [comment]
Let's chat about it here and then when we have some actionable ideas, we can create an issue or issues to address them.

Thoughts:
What pages do we want links on and what should the call for funding look like?
Do we want a dedicated page on the website for funding or is community bridge fine?
What do we use the funding for? Should we highlight that on a page?

**Comment by mpgjon** [comment]
Would love to find out if any of the blocks on this page are embeddable via markdown:
https://funding.communitybridge.org/projects/a4a43b66-f707-47b4-97cc-484285c274a8 - it would be great if we could provide a high level "how much have we raised/spent" and "project goals" block that's live data from Community Bridge and then a link to the page on CB for full details.  If they are, it would be nice to wrap context around that in our own page.  

If we can't embed any dynamic data, and still want to do a page, IMHO we'd write something differently that talks about what we achieve(d) on an annual basis most likely. I think that's more of a quarterly or annual financial update page and maybe that's more what we're looking for?  

Personally, I think the Donate menu item is great and probably sufficient (though would be nice if it could be a different color:)

**Comment by klumb** [comment]
Lets research community bridge and see what our options are. 

Markdown is preferred for created website content because it is easier for many to contribute but we do have options other than markdown. The WordPress Github modules we use will also take HTML files and there may be a WordPress plugin we could add. 

@mpgjon, ask and you shall receive, I added some color and a button style element to the donate link.
Please review on site.

**Comment by mpgjon** [comment]
Awesomesauce @klumb !

**Comment by klumb** [comment]
This issue was resolved with the navigation button. We haven't had any requests for more content so I am closing.
