### ISSUE TITLE
Candidate Release Comments (Format and Presentation)

### ISSUE THREAD

**Issue by klumb** [chaoss/website#182]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about the webpage and presentation of the metrics. To make comments about the focus areas and individual metrics, please follow the links in the release tables.

https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by geekygirldawn** [comment]
I love the overall look! I didn't check all of the links, but I did notice that the link to the "Code of Conduct at Event" metric from the [D&I Event Diversity Focus Area](https://chaoss.community/metrics-rc/#user-content-focus-area---event-diversity) is currently 404.

**Comment by klumb** [comment]
Thanks Dawn, I fixed the link.


Cheers, 


Kevin Lumbard, M.S. PMP (he/him/his)
University of Nebraska at Omaha
College of Information Science and Technology
PKI 367

“Design is all about problem solving. So when I see a project without a problem, I create one” - Anonymous Problem Solver

**Comment by GeorgLink** [comment]
I edited the "Release Table", renaming it.
I just checked all the links.

Tasks I see remaining:
-[] fix realtive paths in Evolution metrics for the screenshots
-[] insert Risk metrics and create issues for comments
-[] add a section for the Value WG that links to the repo, like all other areas, but without metrics

**Comment by klumb** [comment]
I think the relative path issue is something the working groups should resolve. Perhaps we can talk about that in the community meeting on June 25th.  

As @geekygirldawn said, relative paths are generally seen as best practice but seeing as these detail pages are being created for release outside of GitHub, I think it is fair to ask that for these pages only, images and links use absolute paths.

**Comment by klumb** [comment]
The tables are not mobile friendly. I am working on a fix.

**Comment by klumb** [comment]
I have implemented a fix to make the tables dynamic and allow for scrolling on smaller mobile devices. @GeorgLink and @geekygirldawn, please review

**Comment by GeorgLink** [comment]
Thank you @klumb the mobile version is better.

Here is another idea: how about reducing the padding in the table on mobile?
+ smaller font ✅
+ force line break ✅

**Comment by germonprez** [comment]
I tried small font but HTML in MD is weird.

**Comment by GeorgLink** [comment]
Yes. Doing it in markdown is not working well due to the import to WordPress.
@klumb is experimenting with CSS formatting in Wordpress - this is delivering the results we want.

**Comment by germonprez** [comment]
Ah!

**Comment by klumb** [comment]
Okay, I have made a few adjustments to column width, line-height, padding, and font size. The tables are pretty dynamic based on device size now. 

The addition of the comment links on the detail pages makes the table comment link a little redundant so on small mobile devices, I have set the last column to disappear. I think it enhances the mobile presentation. Please let me know your thoughts.

**Comment by GeorgLink** [comment]
Excellent! Thank you very much @klumb 

I agree with disappearing the last column on small screens!

**Comment by germonprez** [comment]
Thanks @klumb

**Comment by geekygirldawn** [comment]
It looks like this is done, so I'm going to close this issue.
