### ISSUE TITLE
Software Pages

### ISSUE THREAD

**Issue by klumb** [chaoss/website#184]
I think we need more content on the software and dedicated pages for each one - Grimoire Lab, Cregit, and Augur.

**Comment by jsmanrique** [comment]
I can draft something for GrimoireLab

**Comment by klumb** [comment]
@jsmanrique, that would be great. Thank you!

**Comment by tharun143** [comment]
@klumb I would like to work on this issue. After going through the discussions in the issue I found Augur has already completed. I think the Grimoire lab and credit are left. If @jsmanrique is not working on the Grimoire lab then I will read the existing md file and update the md file with relevant photos. Also, can u suggest me the resources for solving this issue? By reading the existing model of the Grimoire lab gives me the insights to develop it or to work with it in any future projects.

**Comment by klumb** [comment]
@tharun143,
I think we should have a conversation with @jsmanrique and @sgoggins about what they would like these pages to look like. I will bring it up in the next community meeting but we may want to reach out to them on the email list.

**Comment by tharun143** [comment]
@klumb I would like to draft a software page for the Grimoire lab. Which will help me in participating Google Season of Docs. Is there any response in the meeting with @jsmanrique and @sgoggins

**Comment by klumb** [comment]
@tharun143 , please start with the AUGUR page. You can coordinate with @ccarterlandis for the information and links that AUGUR would like to add to the page.

**Comment by tharun143** [comment]
@klumb So, is there any issue for the AUGUR. @ccarterlandis can u explain to me more about my work.

**Comment by tharun143** [comment]
@klumb I have some questions and I listed it below.
1. How much space (characters/words/lines/pages/etc) of content are you looking for? Are there minimum/maximum requirements?

2. Where will this content live? On its own dedicated page? On the "Participate" page? Somewhere else? All/none of the above?

3. Who will this be targeted at? Potential technical contributors? Potential non-technical contributors? New CHAOSS members? Existing CHAOSS members?

**Comment by samanthavenialogan** [comment]
To confirm this is for the blog I was wanting to publish right?

Assuming that is the case here are your answers:

   1. The blog comes in at ~882 words and ~5300 characters.

   2. The blog is listed here
   <https://www.sociallyconstructed.online/blogs/scms-is-an-official-chaoss-metric>,
   but we were wanting to syndicate it so it would live on your page with a
   link to our original blog post and a no index:do follow tag and a canonical
   tag pointing to ours so duplicate content doesn't persist and damage both
   of our SEO.

   3. *As it stands this was what we have for our targets: *
      1. cvj: data analysts and community managers in open-source
      communities and specifically the CHAOSS community - pervasive.
      2. The listing in our content manager is here:
      https://airtable.com/tblqQLrf3uwYtsAco/viw332c3BGyWbxkEB/recDKx00vOvv2kRsk

      4. We were wanting to release this blog concurrent with the podcast
   release on Friday.

Samantha Venia Logan
Co-Founder of SociallyConstructed.Online
307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525

Call me for a free marketing consultation! 307-274-5516

**Comment by klumb** [comment]
Add overview.md file

Edit individual software md files

**Comment by klumb** [comment]
I am closing this and will create an issue for each software group.
