### ISSUE TITLE
Create a page for GSoC alumni

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#215]
I think we should elevate our GSoC students more and showcase that we are actively participating in the GSoC program.

TODO:
- create a page for GSoC, showing a list of our student alumni and their year of graduation. Maybe even short summary, of how they contributed to CHAOSS.

**Comment by germonprez** [comment]
This is a nice idea

**Comment by klumb** [comment]
We can do this when we rework the community page. Discussion is to have multiple pages replace the current community page.

**Comment by GeorgLink** [comment]
Students in 2019 are:

Student | Project
--|--
Parth Sharma | Build CHAOSS Risk and Growth Maturity and Decline Metrics in Augur
Bingwen Ma | Build CHAOSS Risk and Growth Maturity and Decline Metrics in Augur
Aniruddha Karajgi | Implementing CHAOSS Metrics with Perceval
Nishchith K Shetty | Support of Source Code Related Metrics

We'll have to dig up 2018 again.

**Comment by GeorgLink** [comment]
Aniruddha's final report: https://polaris000.github.io/blog/final_report

It is a source of information about the student's achievement and contributions

**Comment by jgbarah** [comment]
I think Aniruddha's report is quite informative about his work, but just in case a short summary is convenient:

"Aniruddha has produced the first complete reference implementation of CHAOSS metrics, starting with data retrieved directly for the repositories (using GrimoireLab/Perceval). The reference implementations are simple pieces of Python code which produces both numeric and time series values for the intended metrics, and are a good complement to understand the details of the semantics of the metric, and how it may be implemented. Aniruddha has also produced an schema for regression testing on the reference implementation, and a simple tool that can analyze the data for a repository and produce the intended metrics. Aniruddha has worked with the metrics produced by the Evolution working group."

For details, I would point to his [final summary post](https://polaris000.github.io/blog/final_report) and to the [reference implementations directory in the wg-evolution repository](https://github.com/chaoss/wg-evolution/tree/master/implementations).

**Comment by valeriocos** [comment]
Find below a short summary of Nishchith's work:

***
Nishchith has integrated [Graal](https://github.com/chaoss/grimoirelab-graal) with [GrimoireLab](https://chaoss.github.io/grimoirelab/) tool chain, which is now able to collect, enrich and visualize code complexity, license and copyright information. The Graal backends used for this integration are `cocom` and `colic`. The former obtains code complexity data via [Cloc](https://github.com/AlDanial/cloc) and [Lizard](https://github.com/terryyin/lizard), while the latter relis on [fossology/nomos](https://github.com/fossology/fossology/tree/master/src/nomos) and [scancode](https://github.com/nexB/scancode-toolkit) to get license and copyright data. 

A video showcasing the results is available on [Youtube](https://youtu.be/RXZeuJt0UXM), while details of the work can be found on Nishchith's [blog](https://inishchith.github.io/blog/2019/08/coding-period-3-11.html).

The upcoming release of GrimoireLab will make this new feature available for all community.
***

**Comment by klumb** [comment]
This can be created as markdown or HTML in the community folder of this repository.

**Comment by tharun143** [comment]
Hey, I am a CSE undergraduate looking forward to bagging GSoC in the coming year. For this, I need to bring familiarity with the CHAOSS community and environment. 
I would like to work on this issue. Can you be more precise about the issue?

**Comment by tharun143** [comment]
@GeorgLink @germonprez I would really like to contribute to CHAOSS. Can u guys describe me more about the issue

**Comment by germonprez** [comment]
Hi @tharun143. Thanks for your interest in this. I've tagged @klumb who can likely help the most. He is responsible for the web site, which is where this information would be provided. 

Kevin, the idea is to just have a bottom part of the board page with an Alums(?) Former Board Members(?). Jesus GB would be the one on that list.

**Comment by GeorgLink** [comment]
Thanks @tharun143,

We use markdown files as the source for our webpages. For this issue, you could create a pull request to add a `gsoc-alumn.md` file to https://github.com/chaoss/website/tree/master/Community

In a first iteration, the file could contain at least the following structure:

```markdown
# CHAOSS and Google Summer of Code Alumni

## 2020 (repeat for all previous years)
* (list of GSoC students that year)

```

@klumb can then create the page on our website and pull in the markdown file.

In another pull request, the file could be extended to include additional information, such as the project title, a project description, links to blog posts, links to the student's LinkedIn or Twitter profiles... (you decide).

A source of information could be the mailing list archives.

**Comment by GeorgLink** [comment]
We may actually name the page differently, because we are adding Outreachy this year.

**Comment by germonprez** [comment]
Ah! I totally misread this as a page for tracking former board members :/

**Comment by klumb** [comment]
Thanks, @germonprez, and @GeorgLink!

@germonprez, it does make sense to have a former board members list as well. This would be a separate markdown file that I would add to the bottom of the current board page. If you are requesting this, I will create an issue for it. 

@tharun143, the information @GeorgLink has provided about the process is accurate. I am happy to chat with you about this further and will be happy to review the work and help coordinate the move to the website.  

Regarding the data for the page, this issue was created by @GeorgLink so I would defer to him on the specific content and structure of the markdown file.

**Comment by germonprez** [comment]
@klumb ... yes a new issue for this would be excellent (board member alums). Thanks.

**Comment by tharun143** [comment]
Well, first of all, thanks for the response. What I understood from the above discussion is that I have to create a md file with the list of GSoC students. In another pull request, I have to include additional information, such as the project title, a project description, links to blog posts, links to the student's LinkedIn or Twitter profiles... 

Okay, the source for the information is archived mails. 

It's cool guys I will work on it. Thanks for the awesome reply @GeorgLink @germonprez @klumb 
I am really super excited to work with you guys and I feel it's not correct to chat with you guys in comment section. So, I would like to join your chat rooms. Are there any chat rooms like that? If yes tell me I will join in tot he channel and I will post my doubts and update my info on the channel.

**Comment by GeorgLink** [comment]
Thank you. Just to clarify. I suggest two pull requests to have smaller chunks of work and to give you faster feedback but it's all the same file.

**Comment by tharun143** [comment]
Cool, I have sent the md file as a PR and will update the same md file with the additional information.
I have added this year's current GSoC 2020 students and added another column for the mentors. For the second PR, I am planning to include the information s blocks because if it looks like a table then it will be lengthy.

**Comment by tharun143** [comment]
@klumb do you guys need the info only 2018 & 2019 GSoC students or the current 2020 students too?

**Comment by tharun143** [comment]
@GeorgLink I hope you found the PR for this issue and I hope you like the format of the md file. If there are any suggestions or if there is any additional information need to be added please tell me. I will update the PR.

**Comment by GeorgLink** [comment]
Thanks @tharun143. 
I provided feedback on the pull requests.
It sometimes takes a couple of days to provide feedback.

**Comment by GeorgLink** [comment]
> do you guys need the info only 2018 & 2019 GSoC students or the current 2020 students too?

Please add the current 2020 GSoC and Outreachy students if you can.

**Comment by tharun143** [comment]
Do I need to make another separate PR for the 2020 GSoC students and Outreachy students or continue with the same PR?  Sorry for mentioning you so many times. I am super new with contributing to orgs idk that it would take a couple of days for the review btw how is your vacation @GeorgLink . What is the source of information for Outreachy students?

**Comment by tharun143** [comment]
@GeorgLink I have submitted anew PR #321 for this issue. I updated the md file as per your suggestion btw the handy book is helpful for proper documentation.

**Comment by GeorgLink** [comment]
> Do I need to make another separate PR for the 2020 GSoC students and Outreachy students or continue with the same PR? 

You can update the same PR by pushing new commits to the branch that the PR was created from.

**Comment by GeorgLink** [comment]
> What is the source of information for Outreachy students?

https://www.outreachy.org/alums/

**Comment by GeorgLink** [comment]
> Sorry for mentioning you so many times. I am super new with contributing to orgs idk that it would take a couple of days for the review btw how is your vacation @GeorgLink.

No worries. I had a good vacation. Thanks for asking.

**Comment by tharun143** [comment]
> > Do I need to make another separate PR for the 2020 GSoC students and Outreachy students or continue with the same PR?
> 
> You can update the same PR by pushing new commits to the branch that the PR was created from.

Sorry, I just deleted the local repo. So I forked and clone again and sent a new PR btw so sweet to here that you had a good vacation.

**Comment by tharun143** [comment]
@GeorgLink I updated the file. THANKS.

**Comment by GeorgLink** [comment]
> Sorry, I just deleted the local repo. So I forked and clone again and sent a new PR btw so sweet to here that you had a good vacation.

I used to do that too. Now I just leave the master branch untouched and pull in changes from the upstream repo into my local master branch. Then I create [feature branches](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) off of that updated master branch.

**Comment by tharun143** [comment]
@GeorgLink yeah I should read this. I am a bit confused. But it's a great experience working with you. <3

**Comment by GeorgLink** [comment]
Well, congratulations on figuring out how GitHub and git work and getting your first PR accepted (soon to be merged).  After reading about feature branches, I can also recommend the following chapter on working with forks: https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

**Comment by klumb** [comment]
We are live on the website. Nice job!

https://chaoss.community/chaoss-mentorship/
