### ISSUE TITLE
Link to IRC channel

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#229]
The /participate page has the IRC channel listed.

The easiest way to participate in the IRC channel is to use the web interface provided by freenode. 

I propose to turn the IRC text on the /participate page into a link that points to: 
> https://webchat.freenode.net/?channel=#CHAOSS-community

**Comment by jgbarah** [comment]
I think that's a good idea.

**Comment by jsmanrique** [comment]
I was trying to fix this, but I could not find the .md file where that is written. Any help?

**Comment by germonprez** [comment]
I'm guessing would be something to add to this page (I don't see it either): 

https://github.com/chaoss/website/blob/master/Participate/How-to-participate.md

@klumb ?

**Comment by klumb** [comment]
Thank you @jsmanrique I think the text you added is appropriate. In regards to the module at the bottom of the page, because it is just one line of text, it doesn't have an MD file yet. I have made that requested change through WordPress.

**Comment by GeorgLink** [comment]
Thank you very much!
