### ISSUE TITLE
Broken link to GrimoireLab dashboard

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/website#237]
In the software page, under GrimoireLab description there is a link to `GrimoireLab eating GrimoireLab` that is not anymore working.

Would it be nice to have there the link to [CHAOSS GrimoireLab dashboard](https://chaoss.biterg.io)?

**Comment by germonprez** [comment]
Can you issue the PR off of this?

**Comment by jsmanrique** [comment]
> Can you issue the PR off of this?

Yes, I have done it: #238
