### ISSUE TITLE
Broken link to chaoss.biterg.io

### ISSUE THREAD

**Issue by parthsharma2** [chaoss/website#241]
The link to `chaoss.biterg.io` on the [participate page](https://chaoss.community/participate/) is broken. The link directs to `https://chaoss.community/participate/chaoss.biterg.io` instead of `chaoss.biterg.io`

**Comment by GeorgLink** [comment]
Thank you for reporting the issue.

The issue can be fixed with a pull request to change the file:
https://github.com/chaoss/website/blob/master/Participate/software-dashboard.md

@parthsharma2 would you like to create the pull request?

**Comment by parthsharma2** [comment]
Sure, i'll make a PR
