### ISSUE TITLE
Update Augur weekly meeting details

### ISSUE THREAD

**Issue by parthsharma2** [chaoss/website#242]
On the [participate page](https://chaoss.community/participate/), it is mentioned that the Augur WG meets every Tuesday at 10:00 CT. As far as I know, the group meets every Wednesday at 13:00 CT. 

Also, the link to "check your local time" is broken.

**Comment by GeorgLink** [comment]
You are correct. Thanks for reporting the issue.

Would you like to create a pull request to fix the relevant file? 
https://github.com/chaoss/website/blob/master/Participate/software-augur.md

**Comment by parthsharma2** [comment]
Sure, i'll make a Pull Request :+1:
