### ISSUE TITLE
CHAOSScon website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#246]
Hi @klumb 

In the past, we had a map with the location and a "register" button on the page. If I recall correctly, it was to the right of the "About CHAOSScon" section.

Can we have that again for EU 2020?

Thanks,
Georg

**Comment by klumb** [comment]
Yes, we can add that.

**Comment by klumb** [comment]
@GeorgLink, can you please review the webpage. I have restructured several modules and moved content to make this change.

https://chaoss.community/chaosscon-2020-eu/

**Comment by GeorgLink** [comment]
It looks great. Thank you!
