### ISSUE TITLE
About button link in hero section does not work

### ISSUE THREAD

**Issue by eddiejaoude** [chaoss/website#273]
On the main navigation the **about** url is 

```html
<a href="/about/" aria-current="page" class="sf-with-ul">About</a>
```

But in the hero button it is

```html
<a class="nectar-button large regular accent-color  regular-button" style="visibility: visible;" href="http://about/" data-color-override="false" data-hover-color-override="false" data-hover-text-color-override="#fff"><span>LEARN MORE</span></a>
```

<img width="2998" alt="Screenshot 2020-01-12 12 40 30" src="https://user-images.githubusercontent.com/624760/72218994-0a462a80-3539-11ea-9159-fdd07fe80ded.png">

**Comment by GeorgLink** [comment]
@eddiejaoude,
 Thank you for reporting the issue with our homepage.

@chaoss/content-group will take care of it.

**Comment by klumb** [comment]
Thanks @eddiejaoude & @GeorgLink, I fixed the issue.

**Comment by eddiejaoude** [comment]
Awesome 👍 . Thanks @klumb
