### ISSUE TITLE
Website Release Comments

### ISSUE THREAD

**Issue by klumb** [chaoss/website#279]
Please use this space to list edits that need to be made. 

These edits may include broken links, broken images, and language or structure issues.

Please include the repository and file where the edit needs to be made. The metrics page is part of the website repo. The detail pages belong to the working group repos.

**Comment by klumb** [comment]
https://chaoss.community/metric-contributors/
Common metric
Image is wrong place near "4. New contributors (sort list of contributors by date of first contribution)"

**Comment by klumb** [comment]
https://chaoss.community/metric-review-duration/
evolution metric
Mandatory parameters is bold

**Comment by klumb** [comment]
https://chaoss.community/metric-reviews-declined/
evolution metric
Mandatory parameters is bold

**Comment by klumb** [comment]
https://chaoss.community/metric-code-changes/
evolution metric
Mandatory parameters is bold

**Comment by klumb** [comment]
https://chaoss.community/metric-issue-resolution-duration/
evolution metric

References is the incorrect header size

**Comment by klumb** [comment]
https://chaoss.community/metric-social-currency-metric-system/
Value metric

Visualizations are broken

**Comment by GeorgLink** [comment]
PR #280 removes excess "<"

**Comment by GeorgLink** [comment]
PR https://github.com/chaoss/wg-common/pull/51 fixes image placement in value metric Contributors

**Comment by GeorgLink** [comment]
PR https://github.com/chaoss/wg-evolution/pull/325 fixes Mandatory parameters is bold in evolution metrics Review Duration and Reviews Declined

**Comment by GeorgLink** [comment]
PR https://github.com/chaoss/wg-value/pull/68
(hopefully) fixes the SCMS images

**Comment by GeorgLink** [comment]
Where References section has no references, remove "none" ...

**Comment by GeorgLink** [comment]
PR https://github.com/chaoss/wg-diversity-inclusion/pull/272
removes "none" from Reference sections that have no references to be consistent across all  metrics and working groups

**Comment by GeorgLink** [comment]
**How to reference images?** 
Some images are **relative** paths (e.g., Common: Contributors) 
Other images are **absolute** paths (e.g., Evolution: Code Changes).

The problem with absolute paths is that they point to the "master" branch, and not the release tag. 
I think we would be **safer using relative paths** because I assume (but have not tested) that the relative path is sensitive to the release tag whereas the absolute path referencing master will break once we reorganize a repository.

Is my assumption correct? Should we change all the image URLs?

**Comment by GeorgLink** [comment]
https://chaoss.community/metric-issue-age/
Evolution metric
images broken

**Comment by GeorgLink** [comment]
What should we do with references to other metrics?

For example, [Value: Project Velocity](https://chaoss.community/metric-project-velocity/) references several Evolution metrics. The links are pointing to the Markdown file in GitHub. 

For the release, it would be nicer to point to the released metric, to keep visitors on our website. Sending them to markdown files would seem unexpected.

**Comment by GeorgLink** [comment]
https://chaoss.community/metric-issue-resolution-duration/
Evolution metric
Links to related metrics are broken (404)

**Comment by GeorgLink** [comment]
Some images are stored on third party sites. I found this in RISK metrics that use imagur to store embedded images.

Example: https://github.com/chaoss/wg-risk/blob/release202001/metrics/OSI_Approved_Licenses.md
