### ISSUE TITLE
Add meetings calendar in the participate page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#300]
Can we add the calendar to the /participate page, rather than having a separate page for it?

**Comment by klumb** [comment]
Yes, we could do that. Let's leave this open for a bit to get comments.

I don't remember what the initial reasoning was for having them separate but I think there were concerns.

**Comment by GeorgLink** [comment]
I didn't even remember that we had a separate page and when I looked on the /participate page, I couldn't find a link to the calendar (only in the menu). I like to have fewer pages and rather people scroll. 

The calendar display is also very catchy, so I think it will be good having it at the bottom of the /participate page.

**Comment by klumb** [comment]
My initial thought was to have it on the same page. However, there was a request to have it separate. I believe that was discussed in a community meeting as well.

**Comment by tharun143** [comment]
@klumb @GeorgLink I would like to work on this issue. Is it still open? I would like to contribute to this issue. Can u give me more insights on this issue so that I can know where to add and what style and everything?

**Comment by GeorgLink** [comment]
Hi @tharun143, thanks for offering your help.

What is your opinion on merging the calendar page with the /participate page?

I believe resolving this issue requires special access to the website that only @klumb and I have.

**Comment by tharun143** [comment]
After seeing the participant page I found that the participant page was extensively developed for displaying the working groups and tools in CHAOSS. About the calendar page, it is nice to see that there is a schedule for almost every day. It is superb to see that page.  

I have this opinion regarding the combination of pages, if we combine both the pages then the developers would see the calendar in the same participant page and would know about the schedule they will know about the schedule and feel responsible and will actively participate in the meetings. It will also decrease the chance of skipping the calendar page and the user no need to traverse between pages to find the schedule. Separating this page will also make the developer miss the calendar page. So, I think it would be good to combine the pages. 

This is my opinion. @GeorgLink

**Comment by GeorgLink** [comment]
@tharun143 wrote:
>  I think it would be good to combine the pages.

Thanks @tharun143. I appreciate your analysis and opinion!

----

@klumb wrote:
> My initial thought was to have it on the same page. However, there was a request to have it separate. I believe that was discussed in a community meeting as well.

I looked through the community call meeting minutes and only found on October 1, 2019:
> Embed a calendar on the /community page

I think it's safe to combine the pages and do something different if there are complaints.

**Comment by tharun143** [comment]
@GeorgLink So is there anything in this issue I can do like writing the code for it or only @GeorgLink @klumb could do it as you have access to the site?

**Comment by GeorgLink** [comment]
I don't think there is anything you can do to help at this point.

**Comment by tharun143** [comment]
@GeorgLink Okay I will go through other issues. Thanks!

**Comment by klumb** [comment]
merge content to participate page. 
underneath 1st module

**Comment by klumb** [comment]
this was done on the wordpress side
