### ISSUE TITLE
Add Board Member Alumni to CHAOSS Board Page

### ISSUE THREAD

**Issue by klumb** [chaoss/website#315]
This issue was generated based on #215 

"Kevin, the idea is to just have a bottom part of the board page with an Alums(?) Former Board Members(?). Jesus GB would be the one on that list."

**Comment by tharun143** [comment]
@klumb I would like to work on this issue as I already had an experience with issue #215 and sent a PR (#317 ) for the issue. I hope I could handle this issue btw is there any channel for the community to engage with other than Freenode?

**Comment by tharun143** [comment]
@klumb Can u give me more information regarding this issue. I will do the work and will send the PR. @klumb What is the source of information for this issue?

**Comment by klumb** [comment]
@tharun143, create a markdown file in the  /About folder.

Within the markdown file you just need a title that says Former Board Members.

Underneath it you just need to list the former board members. I don't think we need to provide any detailed information on them or links

This is the list I have. @germonprez am I missing anyone? Is there any other information you want to add?

Former Board Members:
Jono Bacon
Jesús M. González-Barahona
Scott K. Peterson

**Comment by tharun143** [comment]
@klumb I sent a PR #318 for this issue. I will update the md file if there any suggestions btw is there any channel for communicating with you other than commenting in the GitHub?

**Comment by GeorgLink** [comment]
>  is there any channel for communicating with you other than commenting in the GitHub?

I'm listening on IRC and respond there. 
All channels we have are listed on https://chaoss.community/participate/

**Comment by klumb** [comment]
The initial PR was merged. Thanks @tharun143 
After previewing on the website, I am adding three tasks to do before it can go live on the website:

- Resize images to 136x136
- remove link from Peterson and add "Image not available text" or an image that conveys that message.
- Resize title to second level header and names to third level headers

**Comment by tharun143** [comment]
Okay @klumb I will work on this issue.

**Comment by klumb** [comment]
Thanks @tharun143!

I dont think it is possible to resize the images in markdown. I could be wrong but I believe that leaves you with two options - Use HTML for the image links, or resize the images in an editor and re-upload them.

**Comment by GeorgLink** [comment]
In my opinion, the better option is to resize the image file.

**Comment by klumb** [comment]
I was just leaving that same comment @GeorgLink. There are some weird display issues with github markdown, html, and wordpress when used to together, so while HTML may work (and has worked in the past), I can't garaunteed it will display properly on the website in a github markdown file.

**Comment by tharun143** [comment]
@klumb @GeorgLink I have added a PR for this issue. If there are any changes in the PR pls tell me I will update it.

**Comment by klumb** [comment]
thanks! This looks good.
