### ISSUE TITLE
Discussion - Newsletter Process and Inclusion on Website

### ISSUE THREAD

**Issue by klumb** [chaoss/website#316]
Hey All,

I would like to spend some time on website planning and consolidation or closing of old issues.

@germonprez @GeorgLink 

Let us use this issue for website planning and requests and then we can create specific issues based on the discussion.

**Comment by klumb** [comment]
The specific issue I would like to discuss is including the newsletter on the website. The google doc method is time-consuming and redundant and creates an issue with storing the images. Can we streamline this process?

**Comment by GeorgLink** [comment]
How about we download a pdf from the Google doc for the visual and upload on the website only the text, exported from the doc as markdown?

**Comment by klumb** [comment]
I can take a look at that but it still seems process heavy. Are you opposed to creating the newsletter using WordPress built-in blog functionality?

**Comment by klumb** [comment]
Or we could create the newsletter the same way we create metric pages (fully in markdown with images stored on github)

**Comment by klumb** [comment]
using HTML, I could embed a pdf version on the website, but it probably won't be seo or search friendly.

**Comment by GeorgLink** [comment]
Hm... maybe I'm missing something or not understanding correctly. I am not opposed to or in favor of any particular solution.

I am also open to writing the newsletter in something other than a google doc.

What would be the easiest process for you?

**Comment by klumb** [comment]
@GeorgLink, I don't think you are missing anything, I would just like to have a discussion about streamlining the process. I am open to many options. Maybe we can chat about the workflows that are associated with each process. My goal would be to make the process as easy and as open as possible. The Wordpress option would be the easiest on my end but it is non-transparent for the project.

**Comment by germonprez** [comment]
I'm all for any change that works for the website. The one thing that we need to make sure is that the newsletter can be easily copy and pasted into an email.

**Comment by tharun143** [comment]
@klumb @germonprez @GeorgLink Is there anything I can help with this issue or is it something inside issue?

**Comment by germonprez** [comment]
@tharun143 you are more than welcome to help out. Perhaps you could take a look at the website and tell us things that appear to be broken or have outdated information.

**Comment by klumb** [comment]
@tharun143 we are using this issue to discuss possible changes and new features. You are welcome to add your ideas and opinions here. If tasks are created from these discussions, individual issues will be created for them.

**Comment by klumb** [comment]
see letter #352
