### ISSUE TITLE
Request to get my article featured on CHAOSS Website Blog

### ISSUE THREAD

**Issue by thecraftman** [chaoss/website#319]
Good day all,

I got accepted as an Outreachy intern for CHAOSS, we are expected to blog every 2 weeks. The articles are meant to be featured in the community website blog or any blog currently maintained by the community. 

I wrote my first article on "How i got accepted into the Outreachy Internship". Please read here 

https://docs.google.com/document/d/1vF69kwXMYtuzl9S0jXyOyS0AeSDga9SJet054ooIIWU/edit?usp=sharing

**Comment by germonprez** [comment]
Thanks @thecraftman ... @klumb what is the best way to get these published?

**Comment by GeorgLink** [comment]
Hi @thecraftman, thank you for proactively writing blog posts.

Please create a pull request that adds a markdown file of your blog post to: 
https://github.com/chaoss/website/tree/master/Community/News

You can export markdown from google doc with a plugin.

The process is:
1. pull request to add a markdown file 
2. @klumb creates and publishes blog post that pulls content from markdown

**Comment by klumb** [comment]
Yep, that is the process, tag me in the PR so that I know to push it to the website.

**Comment by GeorgLink** [comment]
I documented the process for all mentees to follow: https://github.com/chaoss/governance/blob/master/community-handbook/website.md#add-a-blog-post

**Comment by thecraftman** [comment]
Hello @klumb @GeorgLink I've created the PR thanks

https://github.com/chaoss/website/pull/320

**Comment by klumb** [comment]
Thanks, @thecraftman as soon as the PR is merged I will pull it to the website and announce it on the email list.

**Comment by klumb** [comment]
We are live on the Website. Nice Job!

https://chaoss.community/blog-post/2020/05/14/outreachy-blog/
