### ISSUE TITLE
Update About Page

### ISSUE THREAD

**Issue by klumb** [chaoss/website#322]
About/who-are-we.md

Update language to reflect current terminology. For example, we no longer use the term software commitee or metrics commitee. 

Also, the workgroup count is incorrect.

**Comment by tharun143** [comment]
@klumb I would like to work on this issue. According the description of this issue, I need to rewrite the who-are-we.md file which should suites the current terminology and also I need to update the workgroup count. Regarding the workgroup count can I have the resource for it.

**Comment by klumb** [comment]
@tharun143 there are 5 working groups

**Comment by tharun143** [comment]
@klumb I have sent a PR with minimal changes. Tell me if you want to include anything else. I will try to improvise it.

**Comment by klumb** [comment]
resolved with #356, #357, #359, #360
