### ISSUE TITLE
Update Participate Page

### ISSUE THREAD

**Issue by klumb** [chaoss/website#324]
Add link to CHAOSS podcast in Participate/How-to-participate.md

Should we add a markdown file for the ecosystem group? @GeorgLink 

Please add any other updates to the page to this issue

**Comment by GeorgLink** [comment]
> Add link to CHAOSS podcast in Participate/How-to-participate.md

Good idea.

> Should we add a markdown file for the ecosystem group? @GeorgLink

Yes. You can take the description from the WG's repo.

**Comment by germonprez** [comment]
We also need to include the Asia-Pacific call.

**Comment by klumb** [comment]
Add seperate markdown:
- podcast markdown 
- ecosystem user group
- asia pacific call

**Comment by tharun143** [comment]
@klumb @GeorgLink Can u provide me links for adding and can u tell me the location where to add in the website precisely.

**Comment by GeorgLink** [comment]
Thanks @tharun143, I believe these changes require access to Wordpress. Maybe Kevin knows something you can help here.

**Comment by tharun143** [comment]
@GeorgLink Ok!

**Comment by klumb** [comment]
@tharun143 the first three items in that list you can do. 
the file is Participate/How-to-participate.md

https://www.youtube.com/c/CHAOSStube
https://podcast.chaoss.community/
https://twitter.com/CHAOSSproj

**Comment by klumb** [comment]
@germonprez created the asia pacific call module in #354 
The podcast markdown file needs to be created 
The ecosystem module needs to be created
You can do them but I don't have the information on them so you would have to figure it out based on the information that exists on the website currently and what the other participate modules look like.

**Comment by tharun143** [comment]
@klumb I am thinking to update the CHAOSScon link too. Because the CHAOSScon is redirecting to the previous CHAOSScon Europe 2020. If it's ok I will add it.

- Regarding the podcast do I need to create a separate md file? If yes, where and what should I need to include? and I didn't get what is an eco-system module.

**Comment by klumb** [comment]
PR #387 resolves this issue 

@tharun143 feel free to update the chaosscon link.
