### ISSUE TITLE
Menu has an error for GB members page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#328]
The menu entry is mislabeled

See picture:

![Screen Shot 2020-05-15 at 8 51 56 AM](https://user-images.githubusercontent.com/8862021/82057762-71135600-9689-11ea-8a25-bc18f85eab26.png)

**Comment by klumb** [comment]
this has been fixed

**Comment by klumb** [comment]
Thanks for finding the issue @GeorgLink

**Comment by GeorgLink** [comment]
Thanks for fixing.
