### ISSUE TITLE
IFTTT: new blog post --> tweet

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#332]
For CHAOSScast, I have an IFTTT set up that will automatically tweet about new episodes, once they appear on the RSS feed. 

Example: https://twitter.com/CHAOSSproj/status/1256137855606444032?s=20

How about we set something similar up for the CHAOSS blog? I can do it but wanted your opinion on it first.

/cc @klumb

**Comment by klumb** [comment]
That sounds good.

While I do have access to the Twitter account, the odds of me using it are minimal so automation would be better. I will continue to email that mailing list though.



Cheers, 


Kevin Lumbard, M.S. PMP (he/him/his)
University of Nebraska at Omaha
College of Information Science and Technology
PKI 367

"We build our computers the way we build our cities -- over time, without a plan, on top of ruins" - Ellen Ullman

**Comment by GeorgLink** [comment]
good idea on the email

**Comment by GeorgLink** [comment]
Let's see how it works: 

![Screen Shot 2020-05-19 at 7 47 20 AM](https://user-images.githubusercontent.com/8862021/82328069-032a9f80-99a5-11ea-95b6-fe6bf0d21a80.png)


We can close this issue after we know that the IFTTT works correctly. (after next blog release)

**Comment by tharun143** [comment]
@GeorgLink I think this issue can be closed now. As you have created an IFTTT @CHAOSSproj .

**Comment by klumb** [comment]
Thanks Georg!
