### ISSUE TITLE
Cleanup and Upcoming Events: CHAOSScon 2020 NA

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/website#335]
The page [CHAOSScon 2020 NA](https://chaoss.community/chaosscon-2020-na/) could use a cleanup. I also found some inconsistencies. 

For example, the "Upcoming Events" section lists 2020-EU, which happened in January.

I can add more detail on request!

**Comment by klumb** [comment]
- Remove google map (Kevin)
- Add a message for cancellation. Include alternate ways to participate - meetings, podcast, blog, youtube channel
- update upcoming events page

**Comment by tharun143** [comment]
@klumb Is there anything I could do with this issue. It seems moreover this is a maintainer task.

**Comment by klumb** [comment]
@tharun143 sorry about the late reply. I will take a look.

**Comment by klumb** [comment]
Remove call, schedule, speakers

Add a message for cancellation. Include alternate ways to participate - meetings, podcast, blog, youtube channel

**Comment by tharun143** [comment]
@klumb Is there any way I could help here? I know this issue was self-assigned to you. But if u need any help don't hesitate to call out.

**Comment by klumb** [comment]
@tharun143 you can edit the event-detail.md file.

Add an apologetic message for cancellation. but encourage people to find alternate ways to participate - meetings, podcast, blog, twitter, youtube channel. Include some links.

**Comment by tharun143** [comment]
@klumb I have added a PR regarding this issue #367 Please check and tell me to add any more or format.

**Comment by Nebrethar** [comment]
Thanks @tharun143 !!
