### ISSUE TITLE
Hiring a Community Manager no long needed

### ISSUE THREAD

**Issue by tharun143** [chaoss/website#338]
I think CHAOSS is no longer accepting applications for a community manager. Maybe I think a little bit clean up should require for the website.

> This job has expired on indeed

![Screenshot (180)](https://user-images.githubusercontent.com/41537996/82369474-b55d7800-9a34-11ea-9d19-e5dfa71726f4.png)

**Comment by klumb** [comment]
removed from navigation. Thanks
