### ISSUE TITLE
Adding a Dynamic feature to display tweets.

### ISSUE THREAD

**Issue by foundjem** [chaoss/website#344]
Currently, the CHAOSS website is well structured and detailly designed. However, in the tweet section, tweet contents remain static. Moreover, the visibility to know that there is a scrolling bar is rather not evident. 

Given that, we should design our artifacts with diverse users in mind, I suggest we add a dynamic mechanism, which could probably display the tweets automatically with a speed level that we can define here, to accommodate everyone.  

Signed-off-By: Armstrong <foundjem@ieee.org>

**Comment by GeorgLink** [comment]
The section in the website currently shows the newest tweets which changes as the @CHAOSSproj account tweets and re-teweets. 

I don't think we need to signify that there is scrolling possible.

**Comment by klumb** [comment]
Hello @foundjem could you provide an example of what you would like to see.

**Comment by klumb** [comment]
Closing this as the conversation has gone stale. Please reopen if the issue if this feature is desirable.
