### ISSUE TITLE
Add Funders to website footer

### ISSUE THREAD

**Issue by klumb** [chaoss/website#353]
CHAOSS project is sponsored by the 

Alfred P Sloan

**Comment by klumb** [comment]
@germonprez - Waiting on permission from Sloan?

**Comment by germonprez** [comment]
We are OK. https://sloan.org/about/press#tab-logos

Use the horizontal one and make sure to include: 

Thanks and  the Alfred P. Sloan Foundation does not support, endorse, or otherwise certify the results of Foundation-supported work.

**Comment by germonprez** [comment]
@klumb is this something you can do?

**Comment by klumb** [comment]
I am trying to sort out what it will look like in the footer. The footer currently has a grey background. Adding an image to it is problematic. 
If you have design thoughts please let me know.

**Comment by klumb** [comment]
@germonprez,
Please take a look at this
https://chaoss.community/

**Comment by germonprez** [comment]
LGTM
