### ISSUE TITLE
Update links on participate page

### ISSUE THREAD

**Issue by klumb** [chaoss/website#361]
- [ ] edit chaosstube link

- [ ] add chaosscast link

**Comment by tharun143** [comment]
@klumb I will work on this issue. Can u tell me where to add the links precisely?

> Follow us on our YouTube channel

I think I should add the chaosstube link here and WAB the chaosscast link where should I need to add it? 

Maybe I will add it under the chaosstube link. BTW can u send me the links? So I could add and edit the URL's.

**Comment by klumb** [comment]
This is a duplicate issue. Please see #324
