### ISSUE TITLE
Augur links broken

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/website#369]
Following links on Augur page ( https://github.com/chaoss/website/blob/master/Software/augur.md
) are broken on page:

1. Getting started with Augur - https://oss-augur.readthedocs.io/en/master/getting-started/getting-started-toc.html

2. Augur Data Collection - https://oss-augur.readthedocs.io/en/master/data-collection/data-collection-toc.html

**Comment by klumb** [comment]
Fixed by #371
