### ISSUE TITLE
Include disclaimer in metric release

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#372]
Before the metrics, we want to include a disclaimer on the website and the PDF. 

We can refine what it looks like during the comment period.

> **Disclaimer:**
> 
> The CHAOSS project recognizes that there are ethical and legal challenges when using the metrics and software provided by the CHAOSS community. The particular challenges arise in the use that is specific to your context. 
> 
> * **Ethical challenges** exist around protecting community members and empowering them with their personal information.
> 
> * **Legal challenges** exist around GDPR and similar laws or regulations that protect personal information of community members.

**Comment by klumb** [comment]
This is on the main metrics page?  On the 
release/########/metrics-head-rc.md markdown page?

**Comment by GeorgLink** [comment]
That’s a place we can add it.

Let’s try it out and see how we like it.

**Comment by klumb** [comment]
This was resolved in the head markdown file
