### ISSUE TITLE
Clarify Metrics Landing Page

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#374]
When a user clicks on https://chaoss.community/metrics, they currently see this: 

<img width="1200" alt="Screen Shot 2020-06-25 at 10 49 52 AM" src="https://user-images.githubusercontent.com/57594/85742932-a623b700-b6d1-11ea-8b51-7a8e3e3fd39e.png">

This is a little confusing because this page is intended to be a comprehensive list of all the metrics (right?) and in the first sentence of the doc, it explains that this is only a subset of all the metrics. But it isn't clear where we can see a full, comprehensive list of the metrics regardless of release date.

I think this could be clarified because someone just coming to see all our metrics won't necessarily be concerned about when the metric was released, just what is available. 

Since this paragraph will appear on the "Current Release" page, can we rework this landing page paragraph into something like this? 

>The CHAOSS project has developed and defined the following metrics to measure and track data around open source community health in projects and events. CHAOSS uses a Goal-Question-Metric format to present metrics; individual metrics are released based on identified goals and questions. We have sorted metrics into 5 Focus Areas below. If you would like to learn more and discuss different metrics please visit the working group repositories (linked below), or to learn more about each metric, we encourage you to click on the metric's detail page for definitions, objectives, and examples.

Thoughts?

**Comment by germonprez** [comment]
Thanks for catching this! Agreed, this is a list of all metrics and the text can be changed to reflect that.

**Comment by klumb** [comment]
The page is a comprehensive list of the metrics **CHAOSS** has released. 

That first sentence was meant to be a disclaimer that CHAOSS released metrics are not a definitive list all of metrics. This is far from a comprehensive list of metrics. It is a small subset of many possible metrics. CHAOSS is working to define more and many users who visit the page may have metrics they use that don't appear on our page. 

We can edit it to make this more clear but I believe the disclaimer is important.

**Comment by ElizabethN** [comment]
@klumb oh, that makes sense! I agree that the disclaimer is important and should be somewhere. Maybe we could move that around?

I was also a little confused by the "Release" heading, in that I wasn't sure if the metrics were just the ones from the latest release, or if they were a comprehensive list of the ones CHAOSS has released to date. Does that merit some clarification too?

I may be the edge case here, so I appreciate you letting me explore this a little! 🙌

**Comment by klumb** [comment]
The language is likely a holdover from the previous release process - The list was the definitive list of metrics that CHAOSS has released up to date but all of the metrics on the list went through the review process for every new release period even if they weren't a new metric. So for each release, all CHAOSS metrics were checked and could be edited through the comment period. This was not really a static list that we would append to but more a of a dynamic list that was fully editable and a snapshot was taken at a period of time. Thus each release was a singular event and dated. 

This is not a defense of how it is written now. Just a possible explanation. I am always happy to edit and change the wording if it is unclear or even change processes. I will add this to the list of edits for the upcoming release.

**Comment by klumb** [comment]
The page was edited for clarity. Closing this issue, for further comments, please use #376 or the associated PR

**Comment by ElizabethN** [comment]
🤘 thank you so much for taking this into consideration @klumb! You rock :guitar:

**Comment by klumb** [comment]
Let chat about this some more during the content meeting on the 6th
