### ISSUE TITLE
Create Grimoirelab markdown page for the website software page(s)

### ISSUE THREAD

**Issue by klumb** [chaoss/website#388]
The website is the first place many people look when they are investigating CHAOSS. I have gotten feedback from newcomers that they are confused about how the software is connected to the project. Additionally, they have said they have a hard time figuring out which software to contribute to and where to contribute.

I propose we create a one-page markdown file that can provide basic information, visualizations, and important links for each of the software projects. 

@GeorgLink could you help coordinate this?

**Comment by samanthavenialogan** [comment]
I left a comment in another spot I believe but I'd definitely do a homepage audit on all of the pages.  You can adapt this rubric to your needs but to be honest with you I still have trouble knowing what I'm looking at as a noncoding member.  -shrug-

https://www.digitalmarketer.com/blog/landing-page-optimization-conversion/

**Comment by klumb** [comment]
Marketing audit has been added to our todo list - issue is #415 

@GeorgLink Augur has updated their md file. Would you be able to help get content for the Grimoire lab file prior to marketing audit?

**Comment by GeorgLink** [comment]
I see Augur has a new description: https://chaoss.community/software/

Here's the file that needs updating: https://github.com/chaoss/website/blob/master/Software/grimoirelab.md

Not sure when I can do this. I will cross-post it on the GrimoireLab repo in case someone else can pick this up.

**Comment by klumb** [comment]
Done

Thanks all
