### ISSUE TITLE
Create Augur markdown page for the website software page(s)

### ISSUE THREAD

**Issue by klumb** [chaoss/website#389]
The website is the first place many people look when they are investigating CHAOSS. I have gotten feedback from newcomers that they are confused about how the software is connected to the project. Additionally, they have said they have a hard time figuring out which software to contribute to and where to contribute.

I propose we create a one-page markdown file that can provide basic information, visualizations, and important links for each of the software projects.

@sgoggins can you help coordinate this?

**Comment by samanthavenialogan** [comment]
If i'm being honest I feel like a page audit from a marketing perspective may help make it a lot more succinct.  Although you're not necessarily selling a product on this site, adapting the audit I've linked here seems like a good idea to figure out where you're losing out on logical consistency. I struggle a lot with the site as it stands as a noncoding member and maybe this is one of those areas I can help :) 

https://www.digitalmarketer.com/blog/landing-page-optimization-conversion/

I'd throw a few people that are not as familiar with the community at this rubric and see what comes up ^^ I'd also be more than happy to run an audit on behalf of SociallyConstructed.Online.

**Comment by klumb** [comment]
Thanks @samanthavenialogan I am going to open a new issue for a marketing audit for the website.

Any further input you have would be appreciated.

**Comment by klumb** [comment]
Thanks @sgoggins PR #394 partially resolved this issue.

**I am leaving this open with a request for some image content.**

**Comment by klumb** [comment]
Done 

Thanks all
