### ISSUE TITLE
Add "Metrics Programs" and rethink Metrics menu

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#391]
We need a place to represent the metrics programs.

Programs are:
* D&I Badging
* Community Reports
* SCMS (ideation stage)

They may be included in the Metrics menu item. Proposal:

* Metrics
  * Metrics Programs
  * Metrics Definitions (now: Current Release)
  * Release History (now: Release Notes)

**Comment by GeorgLink** [comment]
Thanks @klumb for updating the current menu entries!

**Comment by klumb** [comment]
Definitions and history have been changed. I will create programs when I have content.

**Comment by klumb** [comment]
This is being called initiatives now
