### ISSUE TITLE
Review Website For Inclusivity

### ISSUE THREAD

**Issue by klumb** [chaoss/website#408]
- [ ] **Color-blindness**  
**https://github.com/chaoss/wg-diversity-inclusion/issues/197**   

To ensure CHAOSS is inclusive and accessible, dashboard layouts, and front end components should be reviewed for compliance with color-blindness development standards.  

There's a good test filter service here that can be used to test pages: https://www.toptal.com/designers/colorfilter  

Acceptance Criteria should include:  
- Given that a component of CHAOSS has a front end page
- When that page is reviewed using a color-blindness filter
- Then that page is still readable for color-blind users

For pages that need changes in order to be accessible, separate issues should be opened:)  

- [ ] **Visual Impairment**  
**https://github.com/chaoss/wg-diversity-inclusion/issues/198**  
To ensure CHAOSS is inclusive and accessible, dashboard layouts, and front end components should be reviewed for accessibility by visually impaired users.  

Acceptance Criteria should include:
- Given that a component of CHAOSS has a front end page
- When that page is reviewed using for browser Zoom (at minimum)
- Then that page is still navigable and readable for visually impaired users

For pages that need changes in order to be accessible, separate issues should be opened:)

- [ ] **Gender Inclusivity**
To ensure CHAOSS is inclusive and accessible, dashboard layouts, and front end components should be reviewed for gender inclusivity. 

https://gendermag.org/ may be an appropriate tool for this review.  

Acceptance Criteria should include:  
- Uncertain about acceptance criteria at this time  

For pages that need changes in order to be accessible, separate issues should be opened:)

**Comment by seun-beta** [comment]
Hello @klumb any update on the inclusivity audit?

**Comment by klumb** [comment]
There hasn't been movement on this so I am closing this so the discussion can begin anew
