### ISSUE TITLE
Review Website (Marketing Audit)

### ISSUE THREAD

**Issue by klumb** [chaoss/website#415]
**From @samanthavenialogan #389 :**
If i'm being honest I feel like a page audit from a marketing perspective may help make it a lot more succinct. Although you're not necessarily selling a product on this site, adapting the audit I've linked here seems like a good idea to figure out where you're losing out on logical consistency. I struggle a lot with the site as it stands as a noncoding member and maybe this is one of those areas I can help :)

https://www.digitalmarketer.com/blog/landing-page-optimization-conversion/

I'd throw a few people that are not as familiar with the community at this rubric and see what comes up ^^ I'd also be more than happy to run an audit on behalf of SociallyConstructed.Online.

**Comment by klumb** [comment]
Linking this to our Inclusivity Review #408

**Comment by samanthavenialogan** [comment]
Let me know how this goes and if you have any questions.

Samantha Venia Logan
Co-Founder of SociallyConstructed.Online
307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525

**Comment by klumb** [comment]
Thanks, @samanthavenialogan,  I am looking for volunteers now. We may be able to connect this with our mentorship program or possibly with students from one of the Universities that participate in CHAOSS.

**Comment by ElizabethN** [comment]
@klumb I'm not sure if this would be part of this marketing audit or a separate issue, but we might want to think about including social media previews as something to check and fix.

Example: the D&I Badging Initiative page (https://chaoss.community/diversity-and-inclusion-badging/) -- When posted to twitter, the preview doesn't work super well, so I usually leave it off: 

<img width="634" alt="Screen Shot 2021-02-03 at 3 25 43 PM" src="https://user-images.githubusercontent.com/57594/106805525-cc7cde00-6634-11eb-8ef7-5da1d9947146.png">

Happy to make this a separate issue if it's something that's easy to fix as we come across them. 
Thanks!

**Comment by samanthavenialogan** [comment]
I didn't know this was a thing because I've been absent but I'd be happy to
help with the marketing audit if you like!

Samantha Venia Logan
Co-Founder of SociallyConstructed.Online
307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525

**Comment by klumb** [comment]
Thanks, @samanthavenialogan! We would appreciate your expertise on this. 

We are contemplating including an Outreachy intern on this. 

We also want to do accessibility and inclusiveness audits on the site.

Recommendations from these audits will be used to edit and restructure the website.

**Comment by klumb** [comment]
> @klumb I'm not sure if this would be part of this marketing audit or a separate issue, but we might want to think about including social media previews as something to check and fix.
> 
> Example: the D&I Badging Initiative page (https://chaoss.community/diversity-and-inclusion-badging/) -- When posted to twitter, the preview doesn't work super well, so I usually leave it off:
> 
> <img alt="Screen Shot 2021-02-03 at 3 25 43 PM" width="634" src="https://user-images.githubusercontent.com/57594/106805525-cc7cde00-6634-11eb-8ef7-5da1d9947146.png">
> 
> Happy to make this a separate issue if it's something that's easy to fix as we come across them.
> Thanks!

@ElizabethN I fixed the issue for the D&I Badging page

Each page and blog post has a Meta description or preview connected to it. This content should be added during creation.

This is something the audit should catch but it is something we need to include when we create content on the website.  

If you find any of these or need to me to fix them for twitter previews, let me know.

**Comment by samanthavenialogan** [comment]
Hey yeah,

If I remember correctly you are also running the site via
WordPress. Yoast's free version also injects this code (opengraph meta
data) and requests it on page and blog requests for content to be filled
out so that's not a problem.

But yes, overall this audit will absolutely hit these problems as it covers
standard development, SEO, structure, copy, creative, sitemap, and a few
other things ^^.

Samantha Venia Logan
Co-Founder of SociallyConstructed.Online
307-274-5516  | samantha@SociallyConstructed.Online
6715 Autumn Ridge Dr. Unit 2, Fort Collins CO., 80525


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by klumb** [comment]
Yep, we use yoast

**Comment by klumb** [comment]
There hasn't been movement on this so I am closing this so the discussion can begin anew
