### ISSUE TITLE
No Footer on about>charter,code-of-conduct, governing-board

### ISSUE THREAD

**Issue by kmlhsn** [chaoss/website#417]
Description:
No Footer on charter,code-of-conduct and governing-board under About menu

Expectation:
There should have Footer on charter,code-of-conduct and governing-board under About menu

Steps:
1. Go to https://chaoss.community/
2. Click on About >charter,code-of-conduct and  governing-board

![image](https://user-images.githubusercontent.com/32615215/92001625-ba82d080-ed60-11ea-821b-7bfc448b3780.png)

**Comment by klumb** [comment]
Thank you @kmlhsn

**Comment by klumb** [comment]
Edited on site.

Thank you @kmlhsn
