### ISSUE TITLE
No space between 2 words of menu items under "Community"> CHAOSSblog, CHAOSScast, CHAOSStube and  CHAOSSweekly 

### ISSUE THREAD

**Issue by kmlhsn** [chaoss/website#418]
Description:

No space between 2 words of menu items under "Community"> CHAOSSblog, CHAOSScast, CHAOSStube and  CHAOSSweekly 

Expectation:

Menu items should have space between 2 words e.g.CHAOSS blog

Steps:
1. https://chaoss.community/
2. Mouse over Community

![image](https://user-images.githubusercontent.com/32615215/92005504-60d0d500-ed65-11ea-8720-b5379bdd4588.png)

**Comment by klumb** [comment]
Thankyou @kmlhsn

This was a style choice based on the way the podcast - CHAOSScast - was named.

I am happy to change it but I would encourage discussion on this issue.

**Comment by GeorgLink** [comment]
I’m okay with changing all the menu entries to something more descriptive:

* Blog
* Podcast
* Videos
* Newsletter

**Comment by klumb** [comment]
Changed on website

**Comment by klumb** [comment]
Thanks @GeorgLink  and @kmlhsn
