### ISSUE TITLE
Update Governing Board Bios

### ISSUE THREAD

**Issue by klumb** [chaoss/website#429]
**This is a call to current and Past CHAOSS Board Members.**

Please review your Bio published on the CHAOSS project website.

https://chaoss.community/about/governing-board/ 

If desired, please update your Bio in this issue and we will pull it to the website.

If you would like to update your image, please email me at kmlumbard@gmail.com

**Comment by klumb** [comment]
Archiving

**Comment by GeorgLink** [comment]
Don Marti:
> Don Marti is VP of Ecosystem Innovation at CafeMedia, and a former strategist at Mozilla and former editor of _Linux Journal_. He works on web ecosystem and business issues including collaborative research on the impact of advances in consent management and tracking protection technology. He led the development of an experimental authorized agent service to implement user privacy preferences for Consumer Reports.

**Comment by klumb** [comment]
@GeorgLink - Don Marti has been updated.

**Comment by GeorgLink** [comment]
Thank you :)

**Comment by GeorgLink** [comment]
Please update Ray's bio:

> Ray is the Head of Community at Cube Dev where he is helping to grow the Cube.js community. Prior to Cube Dev, Ray managed open source communities at GitLab and the Linux Foundation. He has over 15 years of experience in the high-tech industry in roles ranging from software engineer, product manager, program manager, and team lead at companies such as EDS, Intel, and Medallia. Ray lives in Sunnyvale, CA with his wife and daughter and all three are loyal season ticket holders of the San Jose Earthquakes soccer team.

**Comment by klumb** [comment]
@GeorgLink Ray has been updated

**Comment by GeorgLink** [comment]
Thank you!
