### ISSUE TITLE
Add link to blog and news from home page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#434]
We have a section "News and Blog" on the home page that has the last three items. It would be great to add a link below them to "read older entries" or something like that. 

![Screen Shot 2020-09-22 at 9 32 04 AM](https://user-images.githubusercontent.com/8862021/93896778-f43b5d00-fcb6-11ea-80f1-4aefb5c75476.png)

**Comment by klumb** [comment]
@GeorgLink please review changes on the homepage

https://chaoss.community/

**Comment by GeorgLink** [comment]
I love it! Thank you very much ♥️

**Comment by GeorgLink** [comment]
I spoke too soon. The buttons don't work for me. On the design, I'm not a fan of the moving text on hover.

**Comment by klumb** [comment]
Well, that's because I didn't add a URL to the button.

Fixed and removed animation

**Comment by GeorgLink** [comment]
It looks and works great! Thank you 😃
