### ISSUE TITLE
Help Find Typos and Errors on the CHAOSS Webpages

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#435]
Help us find typos and errors on the CHAOSS webpages. When you find an issue, issue a PR to make the fix! We appreciate your help :)

**Comment by soulhunter10737** [comment]
Sure, I would like to take it

**Comment by mishrajiharsh219** [comment]
Addressing #435
Hey, I would love to work on that, I think it would be fun.

**Comment by CilgaIscan** [comment]
I would like to work on this @germonprez !

**Comment by snehal199** [comment]
@germonprez Just opened a pr that would fix the typos that I could find!

**Comment by soummo19** [comment]
Sir please review my pr

**Comment by soummo19** [comment]
@germonprez please review my pr #440

**Comment by prajesh007** [comment]
I'm new to open source and was looking for good first issues. Can I take it?

**Comment by klumb** [comment]
Thanks all!

Everyone is welcome to take up this task.

Feel free to make PRs to fix issues or open an issue to ask about the specific typos you find.

**Comment by angelina-tsuboi** [comment]
@germonprez @klumb Hello! I was able to fix some grammar errors on the website.
Please review my PR #459
