### ISSUE TITLE
Update to Community Reports

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#441]
Tagging a few people here: 

@klumb @GeorgLink @ElizabethN 

Kevin, could we do one more update to the form? It should be pretty straightforward. 

Instead of collecting the logo (which seems problematic), could we collect a URL to where the logo is available online? This was Georg's idea.

**Comment by klumb** [comment]
We can certainly update the form. However we don't have any control over the sales force side so we will still need to coordinate with them to collect and recieve the information we need.

**Comment by vinodkahuja** [comment]
@klumb A suggestion: We can use the previous field where we require a list of repos. We deleted that field in the revisions. We can use that field to collect the logo URL.

**Comment by klumb** [comment]
@vinodkahuja That is a good suggestion. If we need to use the URL, that seems like a pretty quick fix.

However, @germonprez I am going to push back a little. There is no reason that we can't get a functioning form and database the delivers the data to us in the exact structure and format that we desire. This issue should be easily fixable once they look at it. 

If we decide that we would prefer a url, @vinodkahuja 's suggestion is quick and easy.

**Comment by klumb** [comment]
@germonprez 

I implemented Vindod's idea on the test page and sent a test form in.

I would like to stress that unless the URL is our preferred method we should just fix file type issue. Which should be very doable.

**Comment by germonprez** [comment]
Ok ok 😊
