### ISSUE TITLE
Link is broken!!

### ISSUE THREAD

**Issue by Shwetago** [chaoss/website#444]
This is the link which is not working: About/project-charter.md

**Comment by klumb** [comment]
Thanks, @Shwetago!

Could you describe where you found this issue?

**Comment by Shwetago** [comment]
There is an About folder. In that folder, there is a file which is project-charter.md. The link mentioned in that file is not working!! 
I hope it helps!! 
Link: https://www.github.com/chaoss/website/tree/master/About%2Fproject-charter.md

**Comment by klumb** [comment]
Thanks @Shwetago 

This is the correct link:
https://github.com/chaoss/governance/blob/master/project-charter.md
