### ISSUE TITLE
Add Asia Pacific Document to Website

### ISSUE THREAD

**Issue by klumb** [chaoss/website#450]
Add Asia-Pacific notes document to Calendar and Website

https://unomail-my.sharepoint.com/:w:/g/personal/mgermonprez_unomaha_edu/EcUfoexbg71Ggk5gtKRVkEwBnBZQDxhe9k4Gyly5yweZ2g?rtime=KyBcL8J12Eg

**Comment by king-gao** [comment]
thanks Klumb. that's awesome.
I have translate into chinese on my blog ,here is link: https://github.com/king-gao/king-gao.github.io/tree/main/CHAOSS%20Asian-Pacific%20meeting

**Comment by MISHANDLED** [comment]
Can you elaborate more on this issue

**Comment by klumb** [comment]
Take a look at the participate page:
https://chaoss.community/participate/ 

Each working group has a module that contains information about participating in the group. The link to the Asia Pacific group's meeting notes is no longer correct. I provided the correct link above. Additionally, we want to add a link to the translated notes repository that @king-gao has provided. 

This is the file that needs to be edited:
 website/Participate/Asia-Pacific-community-call.md

**Comment by klumb** [comment]
This is resolved
