### ISSUE TITLE
404 Errors From Renaming

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#461]
Please see issue at: 

https://github.com/chaoss/wg-evolution/issues/389

**Comment by klumb** [comment]
We will be implementing redirects in the future. Leaving this open as a todo.

**Comment by klumb** [comment]
Add Social listening to the list

**Comment by iamvedant** [comment]
> Add Social listening to the list

Can you please elaborate this.

**Comment by klumb** [comment]
@iamvedant, sorry about the late reply. This task is related to our website migration so it is a maintainer task. Thank you for your interest.
