### ISSUE TITLE
Add Sustain logo on home page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#463]
Sustain sponsors CHAOSScast and we would like to recognize them for it on our home page; underneath Alfred P. Sloan.

**Logo:** https://demo.identihub.co/sustain#/view/icon/element/701

**Text:** The CHAOSS community podcast [CHAOSScast](https://podcast.chaoss.community/) is funded in full by [Sustain](https://sustainoss.org/).

**Comment by RichardLitt** [comment]
LGTM.

**Comment by klumb** [comment]
This is currently being maintained on the WordPress side. Please see page

https://chaoss.community/

Please close the comment if the edit is acceptable.

**Comment by GeorgLink** [comment]
Thanks @RichardLitt  and @klumb !
