### ISSUE TITLE
Prototype metrics menu and display

### ISSUE THREAD

**Issue by klumb** [chaoss/website#466]
Include a WHY you should request the report - a PITCH
- Changes to project
- User data for governance processes 
- Changes to the project over time

Community report web page:
https://chaoss.community/community-reports/ 

Report metrics prototype web page:
https://chaoss.community/metrics-prototype-1/

**Comment by klumb** [comment]
prototype source md:
https://github.com/chaoss/website/blob/master/release/community-report-metrics.md

**Comment by covalentbond** [comment]
Hey @klumb , I was interested to contribute to the project idea of [Build Prototype Metric Display Options](https://github.com/chaoss/governance/blob/master/GSoC-Ideas.md#idea-build-prototype-metric-display-options-on-chaoss-website) as a GSoC student this year. Would like to learn more about the project and can you provide me with some micro tasks to better understand the code base

**Comment by klumb** [comment]
Hi @covalentbond, the tasks will be posted shortly.
