### ISSUE TITLE
Error: Unable to find GitHub content for Social Listening metric

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#471]
I was directed to https://chaoss.community/metric-social-listening/ from our metrics page but I only get the error `Error: Unable to find Github content`

**Comment by GeorgLink** [comment]
I fixed it. The GitHub module on that page was set up to pull from the last `release tag`, but the metric was changed and moved, so we had to pull from `master` branch.

**Comment by GeorgLink** [comment]
@klumb pinging you so you are aware of the change I made

**Comment by klumb** [comment]
Thanks @GeorgLink.

This was a known issue that fell through the cracks because that last WordPress update blocked our edits for a month.

**Comment by GeorgLink** [comment]
Okay, thanks :) -- it's fixed.
