### ISSUE TITLE
Shanghai Meetup

### ISSUE THREAD

**Issue by klumb** [chaoss/website#474]
Hi all, I copied the CHAOSScon EU 2020 event as starting point and created a preview on the website.

I started to make edits to it but will need help so please feel free to edit these documents. Feel free to make new markdown documents if you need them. Just let me know where you want them on the page. 

I am available for a Zoom meeting if you would like. 

Also, feel free to ask if you need me to do anything.

Github repo:
https://github.com/chaoss/website/tree/master/CHAOSScon/2020-Shanghai-meetup

Preview on the website:
https://chaoss.community/shanghai-meetup-2020/

**Comment by klumb** [comment]
@xiaoya-Esther, @germonprez, @ElizabethN, @GeorgLink

**Comment by ElizabethN** [comment]
@klumb I updated the schedule and the speakers pages. Still missing a little info about the speakers, but will add as soon as it's available.

@xiaoya-Esther I wasn't sure who all was on the planning committee so I left that blank for now. Can you fill in this list?

I think the other pages are 👍  as they are.

**Comment by xiaoya-Esther** [comment]
Hi all, I just added the committee list.

**Comment by xiaoya-Esther** [comment]
I just realized the committee on the website usually refers to individuals instead of organizations, so I list part of the community members as I know, please let me know if this is appropriate, and feel free to add more names!

**Comment by MohitPatni0731** [comment]
Can I work on this issue

**Comment by klumb** [comment]
@MohitPatni0731, you are welcome to work on this.

**Comment by MohitPatni0731** [comment]
Hey @klumb 
I am not exactly getting what to do with this issue. Are you available for quick video chat so that I can understand more about the issue and help me to choose my long running project

**Comment by klumb** [comment]
Hi @MohitPatni0731 

This issue was created to coordinate the construction of the Shanghai Meetup webpage. If you weren't in the planning meetings for this event, it may be difficult to work on.

If you are interested in contributing to the website in general, I am happy to meet with you to discuss how you can contribute.

**Comment by MohitPatni0731** [comment]
Yes I want to contribute to the website.
I am available right now to next 1 hour. 
Does this suits you

**Comment by klumb** [comment]
@MohitPatni0731 I am not available for meetings this week or the following. Let's continue this discussion in issue #491

**Comment by klumb** [comment]
Thanks Everyone!
