### ISSUE TITLE
Newcomer Questions and Contribution Coordination

### ISSUE THREAD

**Issue by klumb** [chaoss/website#491]
I am creating this issue to help coordinate newcomer contributions and provide a space for questions. I will update this issue with a list of tasks and issues that are appropriate for newcomers. 

Tasks:

- [ ]

**Comment by klumb** [comment]
Let's schedule a newcomer contribution Zoom meeting for Monday, January 4th. I will announce it on the email list when we get closer to the date. 

What time would work best?

**Comment by MohitPatni0731** [comment]
Hey @klumb 
Can you get me introduced to website development work

**Comment by MohitPatni0731** [comment]
I am available between 11 pm IST to 1 am IST

**Comment by SaranshMaheshwari** [comment]
I am also new to this organization and want to attend this video chat. So I am also available at this time.

**Comment by germonprez** [comment]
Thanks for your interest everyone. I think the best way to meet would be a couple of different ways: 

1) Via Issues that you can find in the respective CHAOSS repositories. Each working group for metrics has its own repository and the same is true for software

2) Join us as we start our 2021 videos calls as a community. 

You can find this information at: https://chaoss.community/participate/

**Comment by klumb** [comment]
To be clear, this issue is about contributing to the website.

@germonprez is correct the best way to get started is to attend video calls. 

This is especially true for website content as most of the planning and discussions take place there.

The next web content meeting is on January Fourth. 

CHAOSS Web-Content Meeting
Scheduled: Jan 4, 2021 at 11:00 AM to 12:45 PM
Location: https://zoom.us/j/4998687533
The CHAOSS content-group meets the first Monday of the month at 11:00 am CT (usually 18:00 CET, check local time)

This is a 1  hour and 45 minute meeting to add content to the website and streamline ongoing processes.

Rather than having a separate meeting for newcomers, I will set aside some time at the end of the regular meeting for new contributor questions.

**Comment by MohitPatni0731** [comment]
Thanks for the update @germonprez and @klumb

**Comment by MohitPatni0731** [comment]
I just realized that I've missed yesterday meeting . What should I do now to get myself introduced to web development or other projects.

**Comment by klumb** [comment]
Hi @MohitPatni0731,
We will have another web content meeting the first week of February. These meetings are very informal and you don't have to talk if you don't want to. At the end of these meetings, we are setting aside some time for newcomer questions and tutorials. 

In regards to the CHAOSS project in general, we have a **community meeting** every Tuesday that is a good place to start.

Check out the calendar here; https://chaoss.community/participate/ 

As a community, we rely pretty heavily on these Zoom meetings so they are really the best place to start.

**Comment by Rishabh-Gaud** [comment]
Hi @klumb 
I am new to this organisation. Can you guide me to help to our organisation. I am here to give contribution much I can.

**Comment by klumb** [comment]
Welcome @Rishabh-Gaud! Please see my previous comment. The Zoom meetings are the best place to start.

**Comment by khushi935** [comment]
Hello everyone, I am new to the organization. I want to contribute and participate in GSOC 2021. I took the basic idea of what is augur software? and now I am confused about how to go ahead and which working group meeting I should attend?
Please guide me.

**Comment by germonprez** [comment]
Hi @khushi935 

Thanks for your interest. You can check out the Augur repos at: 

https://github.com/augurlabs
and 
https://github.com/chaoss/augur

Posting an issue in these repos for an introduction would be a great place to start.

**Comment by khushi935** [comment]
Thank you @germonprez for guiding me.

**Comment by kirtirajsinh** [comment]
Hello, I'm new in this  organization. looking forward to the next call.

**Comment by germonprez** [comment]
Great. You can always check out the Participate page at: https://chaoss.community/participate/
