### ISSUE TITLE
Sharing Community Reports

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#496]
Hi @klumb and @vinodkahuja 

On the community call on Jan 19, 2020 we decided to place all 'okay to share' community reports here: 

https://github.com/chaoss/community-reports/tree/master/sample-reports

Once the reports are there, we can provide links on the (1) Request report page and (2) the front page banner on chaoss.community

**Comment by vinodkahuja** [comment]
Ok. I will Upload one which is ready.

**Comment by klumb** [comment]
@vinod can you provide the links for the pdfs? The links will need to be added to the form page as example reports.

**Comment by aryan-alt** [comment]
Hello,
Can you please elaborate more on this issue?

**Comment by klumb** [comment]
Putting this on hold as we are uncertain about the future of community reports.
