### ISSUE TITLE
Add Link to Community Handbook in Community Section

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#497]
Hi @klumb :wave:!
I noticed I couldn't find a link to our Handbook readily available anywhere, so what do you think about adding a link to it under the Community drop-down list?

For our reference, here's the link to the handbook https://app.gitbook.com/@chaoss-project/s/community-handbook/.

**Comment by klumb** [comment]
I added it the navigation

**Comment by GeorgLink** [comment]
I would prefer we use the URL: https://handbook.chaoss.community/

**Comment by klumb** [comment]
@GeorgLink that was the link I used ( was following the thread in the handbook repo)

Please review on site

**Comment by GeorgLink** [comment]
Awesome!! Way ahead of me 👍
