### ISSUE TITLE
CHAOSScon 2021 link redirecting to the wrong page

### ISSUE THREAD

**Issue by jaskiratsingh2000** [chaoss/website#498]
I was just surfing the website and came across an option "CHAOSScon 2021 Europe, Brussels, Belgium, co-located with FOSDEM 2021" under the **Upcoming Events** section on this page https://chaoss.community/shanghai-meetup-2020/ 
Clicking on the "CHAOSScon 2021 Europe" link, it redirects to the [Shanghai Meetup 2020](https://chaoss.community/shanghai-meetup-2020/)

**Comment by klumb** [comment]
That link actually just stays on the page you are on. 

It was not connected to a CHAOSScon 2021 page because the event was canceled due to the pandemic. 

The event itself should be removed - We have no upcoming events that I am aware of.

**Comment by jaskiratsingh2000** [comment]
Oh okay!

**Comment by AkshadK7** [comment]
Issue this issue still open to work on?

**Comment by klumb** [comment]
@AkshadK7 this issue is still open. Sorry about the late reply.

**Comment by covalentbond** [comment]
@klumb , would like to work on it. Do we need to remove the complete event or just state that the event is cancelled?

**Comment by klumb** [comment]
Remove the Europe 2021 link from the upcoming events section and replace it with "To Be Announced" text.

**Comment by klumb** [comment]
Edit File -  website/CHAOSScon/past-future.md

**Comment by covalentbond** [comment]
hey, also how to build the website locally? We can also update [contrubuting.md](https://github.com/chaoss/website/blob/master/CONTRIBUTING.md) with documentation to setup the repository!
