### ISSUE TITLE
Broken images on CHAOSScast site

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#517]
I don't know if this belongs here or somewhere else, but the images are all broken on https://podcast.chaoss.community/ (except the social media icons). Tried a few different browsers (Chrome and Safari) and it's the same result.

<img width="1152" alt="Screen Shot 2021-02-12 at 4 54 44 PM" src="https://user-images.githubusercontent.com/57594/107826575-195a6600-6d53-11eb-82bb-1cb7a6fbc6c1.png">

cc @GeorgLink @klumb

**Comment by klumb** [comment]
I am unsure if this is the proper place. @GeorgLink is the point of contact for CHAOSS cast, so perhaps he can answer the question.

However, I did take a look and was unable to duplicate the issue with broken images.

**Comment by ElizabethN** [comment]
>I did take a look and was unable to duplicate the issue with broken images

It's on my end then, so weird! Ok I will troubleshoot. 🤔

**Comment by GeorgLink** [comment]
This is a good place to raise the issue. Like Kevin, I can’t replicate it.

**Comment by klumb** [comment]
@ElizabethN are you still having this issue?

If it is resolved please close this issue.

**Comment by ElizabethN** [comment]
I never discovered what the problem was but it seems to have resolved itself. If only all problems were like that! :blush: Closing this issue.
