### ISSUE TITLE
Issue in Styling Of Navigation Bar In Some Screen Sizes

### ISSUE THREAD

**Issue by iamvedant** [chaoss/website#521]
![image](https://user-images.githubusercontent.com/52073576/108462564-d0e6ff00-72a2-11eb-9a3e-5659bfab7625.png)
The Donate button is not displayed properly and search icon is also not visible in a particular screen size

**Comment by iamvedant** [comment]
Does all the styling of this website reside in this repository or is it somewhere else? I am struggling to find out the markdown for navbar.

**Comment by klumb** [comment]
Thank you @iamvedant 

The navigation bar is managed in WordPress.

The page dynamically changes based on screen size. It looks like you are manipulating the window size. If you make the window a little smaller or a little larger it will adjust to the correct display.

**Comment by iamvedant** [comment]
Okay @klumb 
Can you please tell me on which platform can I ask queries. I am trying to explore the CHAOSS Repos and have some doubts. Kindly let me know a proper platform so that I could contribute.

**Comment by klumb** [comment]
@imavedant, Most of the styling and admin is managed in WordPress. Content for the website is managed here in this repo. 

This is the appropriate place for all queries about the website.
