### ISSUE TITLE
Issue in navigation bar

### ISSUE THREAD

**Issue by Aanandgupta** [chaoss/website#524]
The heading that sticks for desktop size screens is missing for mobile devices 
Is that done deliberately if yes then why any specific reason?

![Screenshot (148)](https://user-images.githubusercontent.com/71023799/108542547-e5121700-7309-11eb-94ea-ea7da067b985.png)

![Screenshot (147)](https://user-images.githubusercontent.com/71023799/108543171-bc3e5180-730a-11eb-88bd-07eaac2da984.png)

**Comment by klumb** [comment]
@Aanandgupta mobile page views often display less information than desktop views. This is done for many reasons. In this particular case, it was a design decision made by the WordPress template developers. Since the data is not critical for the page, we have made no effort to override the display.
