### ISSUE TITLE
Community report request form modification

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/website#525]
@klumb I have received a community report request without the requester's first and last name. Can we make at least one field mandatory, i.e., first name? From my experience in my culture, some people don't have a last name. Having at least one field mandatory will serve the purpose.

**Comment by klumb** [comment]
Yes, we can do this. Lets discuss which fields are mandatory in the web content meeting this next week.

**Comment by klumb** [comment]
Edit the form to make name mandatory.

**Comment by MISHANDLED** [comment]
Can you elaborate more on this issue

**Comment by klumb** [comment]
First and last name need to be mandatory fields in the form located at:
https://chaoss.community/community-reports/ 

The file is located here:
 website/Programs/Community-Reports/appmaster.html

**Comment by aryan-alt** [comment]
Hello,
So we have to make the changes in the form section of the community page and make the two fields mandatory, i.e, First and last name, right?
So can I work on this issue?

**Comment by klumb** [comment]
@aryan-alt 

Thank you for the interest. You are welcome to work on it but we generally don't assign people to issues, unless they are complex or require administrative access.
