### ISSUE TITLE
Set up the repository locally

### ISSUE THREAD

**Issue by MISHANDLED** [chaoss/website#540]
Update the docs so that it provides steps set up the repo locally

**Comment by klumb** [comment]
Are these general directions on how to clone and fork a GitHub repository?

**Comment by MISHANDLED** [comment]
How to run the website locally after cloning

**Comment by GeorgLink** [comment]
The https://chaoss.community website is a WordPress website. The
chaoss/website repository is not the website and the website cannot be
built from the repository. The chaoss/website repository contains
supporting documents only.

**Comment by klumb** [comment]
@GeorgLink is correct. While there are ways that we could manage the website code on GitHub we are currently limited by the policies and processes of the Linux Foundation (who supplies our WordPress hosting). We are in the process of migrating the website to a new platform that we will have more control over, however, we will likely maintain the current process as it allows us to collaboratively and quickly edit the content on the site. 

Under our current process, becoming a website maintainer will give you access to the code and administration of the WordPress site. The maintainer creates a blank (lacking content) webpage using WordPress that includes multiple GitHub Modules. Individual markdown files in this repository should map directly to those GitHub Modules (content areas) on the website. We welcome edits to improve the clarity of this process and new documentation that describes this process, style guides, and website structure.
