### ISSUE TITLE
Automation script for fixing typos

### ISSUE THREAD

**Issue by ritik-malik** [chaoss/website#572]
Hi,

While I was hunting for typos yesterday, I thought why not create a script which would automate the task of scavenging typos, wait for manual approval & then fix them automatically.

It would save the task of manual labor in scanning the entire website & making the required changes. I plan to do it by adding a new py script & a bash script.

Pseudo code -
* Traverse all MD files in the website repo recursively
* Make list of blacklisted words which shouldn't be bothered like - `augur`, `chaoss`, `Grimoire`, etc.
* Use the [pyspellchecker](https://pypi.org/project/pyspellchecker/) to detect possible typos & generate most likely substitutes
* Throw all these words in a new file with metadata like filename, line number, hyperlink, etc.
* Then wait for manual approval/changes in this file
* Finally a bash script to replace all these typos automatically by reading this modified file

**Comment by klumb** [comment]
Sounds good, I look forward to seeing this.

**Comment by klumb** [comment]
Thanks @ritik-malik, we don't have any problems with contributors using scripts for this but we don't want to include them in the Repo.

**Comment by ritik-malik** [comment]
sure sure,
This issue is already resolved, I forgot to closed it.

Closing it now
