### ISSUE TITLE
Adding contributors image to README.MD

### ISSUE THREAD

**Issue by Rupesh-2003** [chaoss/website#579]
Adding dynamic contributors image to readme.md

**Comment by klumb** [comment]
Thank you @Rupesh-2003, I like this idea but I am not sure it is needed. The contributors listed here should include those from the image but should also include those that contribute in other ways. The dynamic contributors to the repo is already available through Github so I see this as duplication. 

The contributor list does need to be updated though.

**Comment by GeorgLink** [comment]
I don't like the idea of embedding a third-party service link in our README.

**Comment by Rupesh-2003** [comment]
No problem, I'll look over other open issues
