### ISSUE TITLE
Update CTA on front page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#591]
Update CTA on front page:

![Screen Shot 2021-03-30 at 11 31 46 AM](https://user-images.githubusercontent.com/8862021/113023714-8a12e180-914b-11eb-9c50-f9c507d7eb58.png)

We can put GSoC there now :)

**Comment by klumb** [comment]
Can you provide me some details on what you would like to see?

**Comment by GeorgLink** [comment]
> CHAOSS is participating in Google Summer of Code. Review the project ideas now! 

Link to: https://github.com/chaoss/governance/blob/master/GSoC-Ideas.md

**Comment by klumb** [comment]
Done!

**Comment by GeorgLink** [comment]
Thank yo!
