### ISSUE TITLE
Adding social media links of selected students in mentroship projects

### ISSUE THREAD

**Issue by pankaj892** [chaoss/website#594]
Hey @klumb in the mentorship page on CHAOSS website i found that students who completed GSoD and GSoC recently there is no Linkedin or twitter profile links of them.It would be great if we have them since previous students have them.

**Comment by klumb** [comment]
@vchrombie what do you think?

Github id might be nice... Twitter? Linkedin?

**Comment by vchrombie** [comment]
Hi @klumb @pankaj892, I understand adding any contact details is helpful.

> Github id might be nice... 

I agree with this, we can easily find the github ids of the previous students. We just need to surf the commit history of the interest pages.

> Twitter? Linkedin?

I feel github is enough as we might need to put an extra effort to find and verify the other accounts. Also, there might be a few people who don't have a twitter/linkedin (I know the probability is less, but still). If we have the github, I'm sure you would get their twitter or at least mail id which is enough for contacting them. WDYT?

Also, it would be great if we can define a structure for the projects and revamp all the existing projects to that. We can follow this structure for adding future projects too. We just need to re-use the existing content and add the missing things. I have an example.

---
### Parth Sharma

Parth Sharma successfully completed GSoC 2019.

#### Project Title 

Build CHAOSS Risk and Growth Maturity and Decline Metrics in Augur

#### Project Description

Augur is fully functional prototyping web stack for CHAOSS metrics. It provides structured data mined from git repositories using a plugin architecture that incorporates other open source metrics projects like Facade and FOSSology. The main aim of this project is to extend Augur’s functionality by implementing Risk and Growth-Maturity-Decline CHAOSS metrics and use cases with a focus on the open source community manager use case. This project, with a focus on the community manager use case, will allow open source community managers to leverage Risk and Growth-Maturity-Decline metrics to better manage their communities and projects.

#### Links

- [GitHub @parthsharma2](https://github.com/parthsharma2)
- [Blog Posts](https://parthsharma2.github.io/posts)
- [Project Link on GSoC Website](https://summerofcode.withgoogle.com/archive/2019/projects/5952207168471040/)

---
We have around 18 students. I can help with collecting the links, details and reviewing the PR too. WDYT?

**Comment by pankaj892** [comment]
@vchrombie I agree github id  would be enough as we can easily verify them and we would get their email-ids which would be easy for those who wish to contact them

**Comment by vchrombie** [comment]
> Also, it would be great if we can define a structure for the projects and revamp all the existing projects to that. We can follow this structure for adding future projects too. We just need to re-use the existing content and add the missing things. I have an example.

WDYT @klumb?

**Comment by vchrombie** [comment]
@pankaj892, would you be interested to submit a PR for this?

**Comment by pankaj892** [comment]
@vchrombie  only adding github ids is enough or do i add some more links ? I am interested to submit a PR for this

**Comment by vchrombie** [comment]
I was thinking of revamping the page as per the template I suggested. Moet of the content is already there, you need to re-use it and make it proper. WDYT?

I can help with reviewing and suggestions.

**Comment by pankaj892** [comment]
@vchrombie OK I'll work on it and send a PR review it if any changes are needed let me know

**Comment by vchrombie** [comment]
@pankaj892 can we close this issue as it is resolved?
