### ISSUE TITLE
Add Intro Workshops to Site

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#595]
Hi @klumb! :wave:
 
We are hosting a series of workshops to help people interested in contributing to get up to speed. Would it be possible to put these all on one page under the "Community" drop down navigation, entitled "Workshops"?

I am happy to create the page, but if it's better if you do it, here is the info. Just let me know if I need to create it myself.

**Intro blurb for the top:** 

The CHAOSS community is happy to be hosting a series of introductory workshops for those who are interested in contributing to CHAOSS software (or other open source projects). These are free, virtual workshops, and we have spaces available for attendees as well as mentors. Hope you will join us!

**Here is the full list:**

Date | Type | Topic | Start/End Times | Registration
-- | -- | -- | -- | --
April 6, 2021 | Workshop | Workshop: Configuring Your Computer (Getting Setup for Python Development in CHAOSS & Intro to Github Workflow) | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-april-6-2021)
April 9, 2021 | Workshop | Workshop: Configuring Your Computer (Getting Setup for Python Development in CHAOSS & Intro to Github Workflow) | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-april-9-2021)
April 13, 2021 | Workshop | Workshop: Restful API Development | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-april-13-2021)
April 20, 2021 | Workshop | Jupyter Notebooks: Getting Started | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-april-20-2021)
April 27, 2021 | Workshop | Jupyter Notebook Visualizations | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-april-27-2021)
May 24, 2021 | Workshop | Workshop: Configuring Your Computer (Getting Setup for Python Development in CHAOSS) | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-may-24-2021)
June 5, 2021 | Workshop | Workshop: Restful API Development | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-june-5-2021)
June 19, 2021 | Workshop | Jupyter Notebooks: Getting Started | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-june-19-2021)
July 17, 2021 | Workshop | Jupyter Notebook Visualizations | 8am - 10am CDT, 6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-july-17-2021)
July 31, 2021 | Workshop | Workshop: Configuring Your Computer (Getting Setup for Python Development in CHAOSS & Intro to Github Workflow) | 8am - 10am CDT,6:30pm - 8:30pm IST | [Register](https://ti.to/chaoss/chaoss-software-workshop-july-31-2021)

**Comment by seun-beta** [comment]
@klumb Can I get to work on adding this to the website? What section do you think this should be added to? 

Thank you and happy holidays

**Comment by klumb** [comment]
@ElizabethN will these always be workshops? Or is there another type of meeting that could occur? meetup? hackathon?

Is there a name that would encompass all of those things? Should we remove the workshop column if they are all workshops?

- We will need to create a folder within the community folder called _workshops_ (depends on the question above).
- Within that folder we will need two markdown files - _overview.md_ and _schedule.md_
- The blurb at the top should be put into _overview.md_
- The table should be put into the _schedule.md_ file. It looks like @ElizabethN has already provided it in markdown form so that should be easy.

**Comment by ElizabethN** [comment]
>@ElizabethN will these always be workshops? Or is there another type of meeting that could occur? meetup? hackathon?
>
>Is there a name that would encompass all of those things? Should we remove the workshop column if they are all workshops?

Ah yes. I think in hindsight we should keep the workshops and hackathons on their own separate pages, don't you? We plan on continuing the hackathons for now, and are in the process of scheduling the next 2.

Which means , you're right, we don't need that "workshop" column on this page. 


>We will need to create a folder within the community folder called workshops (depends on the question above).
>Within that folder we will need two markdown files - overview.md and schedule.md
>The blurb at the top should be put into overview.md
>The table should be put into the schedule.md file. It looks like @ElizabethN has already provided it in markdown form so >that should be easy.

@seun-beta thank you for helping with this and getting this on the website! You're a gem. 💎 🙏 If you need anything from me, let me know!

**Comment by seun-beta** [comment]
Thank you @klumb and @ElizabethN for the information. I’ll submit a PR for it today. Just getting out of Easter Holidays. If the are any changes to be made, @klumb would suggest it on the PR.

Thank you once again.

**Comment by seun-beta** [comment]
I have made a PR for the workshops @klumb see #593 . Could we also add a time zone converter and 'add to calendar' as it works on the community call page. I think the 'add to calendar' takes care of daylight savings and time zone problems.

Cheers

**Comment by seun-beta** [comment]
I added it as a subset of the previous pull request I made.

**Comment by seun-beta** [comment]
Hello @klumb . I noticed an error.

https://github.com/chaoss/website/tree/master/Community/Workshop

Should be deleted. It was an initial duplicate I made.

**Comment by klumb** [comment]
Yes, I saw that. Will need to be removed in a future edit.

**Comment by klumb** [comment]
This live on the site now.

https://chaoss.community/workshops/

**Comment by seun-beta** [comment]
Hello @klumb i am getting an error on the workshop page and other pages 
![B5CC2F9D-6D12-45B1-9A42-FFE75FC764F2](https://user-images.githubusercontent.com/51419148/113763220-5880b400-9711-11eb-9f23-637127ed71fc.png)
![338E2AFA-4B35-4F4F-8BD3-CA412F285421](https://user-images.githubusercontent.com/51419148/113763223-5a4a7780-9711-11eb-932b-48242c9690a8.png)

**Comment by seun-beta** [comment]
Hello @klumb i am getting an error on the workshop page and other pages
![Uploading 3B0BB419-DC4D-4468-9CD7-BD858D83D7C6.jpeg…]()

**Comment by klumb** [comment]
Yes, it looks like all GitHub content on the website is down.

I am investigating but this is likely a temporary issue.
