### ISSUE TITLE
Error: Unable to find Github content

### ISSUE THREAD

**Issue by mattwynne** [chaoss/website#601]
Many of the pages on the site now show this error:

For example, the metrics page:
<img width="1258" alt="Screenshot 2021-04-06 at 13 20 52" src="https://user-images.githubusercontent.com/19260/113773466-eb522c00-96da-11eb-8092-0bfdade530b2.png">

**Comment by klumb** [comment]
Thank you @mattwynne, 
I am investigating the issue.
This problem was first observed about 2 hours ago. and is affecting all of the GitHub content on the website.

**Comment by xiaoya-Esther** [comment]
Yes, and I wonder (and afraid of) if this was caused by the new blog post on the Digital Insight Report. Hope not.

**Comment by klumb** [comment]
@xiaoya-Esther , I don't think your blog post could have caused the issue.

**Comment by klumb** [comment]
This issue is now resolved. There was a problem with our GitHub token.
