### ISSUE TITLE
Formatting Inconsistency

### ISSUE THREAD

**Issue by DGomez99** [chaoss/website#607]
Hello, I noticed on the CHAOSS website in the metrics definitions there are formatting inconsistencies in the objective descriptions, such as 
[Diversity Access Tickets](https://chaoss.community/metric-diversity-access-tickets/)
and 
[Board Council Diversity](https://chaoss.community/metric-board-council-diversity/)

I was wondering if the format between the metrics definitions on the website could be standardized as it would give the website a more fluid shift between information?

**Comment by GeorgLink** [comment]
Yes, absolutely, yes! :D

The different formats resulted from different people writing the objectives.

We are open to suggestions for a more consistent objective description format.
