### ISSUE TITLE
Header overlapping with navigation menu on metrics webpage

### ISSUE THREAD

**Issue by yash2002109** [chaoss/website#608]
Hi,

I noticed that the header ("THE LINUX FOUNDATION PROJECTS") on the [metrics](https://chaoss.community/metrics/) webpage is overlapping with the navigation menu.

Refer to the image below for a better understanding.

![website-metrics](https://user-images.githubusercontent.com/77677278/115907478-8fcbc080-a486-11eb-8970-16af87c74015.jpg)

Also, please let me know if I can be of any assistance in fixing this.

**Comment by klumb** [comment]
I can't replicate this on my end using a Mac and - safari, chrome, and firefox.

What browser are you using?

**Comment by yash2002109** [comment]
I'm using chrome, on Windows

**Comment by AtharvaParkale** [comment]
Can i work on this issue

**Comment by klumb** [comment]
Thanks @AtharvaParkale

Can you duplicate the issue @yash2002109 is seeing?

**Comment by AtharvaParkale** [comment]
> Thanks @AtharvaParkale
> 
> Can you duplicate the issue @yash2002109 is seeing?

The same issue faced by me.

**Comment by klumb** [comment]
This is likely a browser issue. I still haven't been able to replicate it on my end but I have seen this same issue in the past. @yash2002109 are you still seeing this problem?

**Comment by yash2002109** [comment]
Yes @klumb, I'm still seeing this issue. I was also able to replicate it on a Mac (Safari), so I'm not exactly sure if it is a browser problem.

**Comment by klumb** [comment]
I still can't see this on my end - using safari, chrome, and firefox. Unable to replicate. 

Does anyone else see this issue or not see it?

**Comment by adithyaakrishna** [comment]
@klumb I can see this, I have a solution for this too. The padding value is set to 10px at top and if we make it zero, the issue gets fixed. But I wasn't able to find the exact place where this section of code is present.

![image](https://user-images.githubusercontent.com/23498248/124508966-95cb0f80-ddee-11eb-80fa-a5a099c694f2.png)

**Comment by klumb** [comment]
This needs to wait until after the website migration

**Comment by klumb** [comment]
Closing this issue. 

If the issue persists, please open a new issue
