### ISSUE TITLE
Content of "Diversity and Inclusion Areas" in main page of CHAOSS metric is missing.

### ISSUE THREAD

**Issue by eyehwan** [chaoss/website#615]
https://chaoss.community/metrics/
![capture](https://user-images.githubusercontent.com/1535756/120911009-1db9de80-c6b6-11eb-9455-d39f3cca2d4d.PNG)

**Comment by klumb** [comment]
Thanks for catching this @eyehwan 

The file name was changed to reflect the working group name change and we didn't make the change on website side. I fixed it.
