### ISSUE TITLE
Link of https://chaoss.community/metric-change-request-acceptance-ratio/ is invalid

### ISSUE THREAD

**Issue by eyehwan** [chaoss/website#616]
https://chaoss.community/metric-change-request-acceptance-ratio/

![image](https://user-images.githubusercontent.com/1535756/120911890-704ac900-c6bd-11eb-8687-e9d53b857435.png)

**Comment by klumb** [comment]
Thanks @eyehwan 
Should be good now

**Comment by eyehwan** [comment]
> Should be good now

That's true. Thanks @klumb for your quick support!
