### ISSUE TITLE
We need to update the ways of participating on the "Participate" page

### ISSUE THREAD

**Issue by xiaoya-Esther** [chaoss/website#622]
As discussed in #621 

We have a slack workplace for communicating.
Also, we hold a Tencent meeting bi-weekly using the tools and platforms that folks from China are more familiar with, intending to mitigate the barrier of participating in CHAOSS community.

**Comment by xiaoya-Esther** [comment]
We have some distributed platforms and channels exclusively for the CHAOSS Chinese community. Here is a summary:

**Slack channel:** https://chaoss-workspace.slack.com/archives/C0258G98SSX

**Bilibili space:** https://space.bilibili.com/1292724697?spm_id_from=333.33.b_73656375726974794f75744c696e6b.1 

**WeChat official account:** 
![image](https://user-images.githubusercontent.com/56542972/125464389-c7e65259-40cd-4e3c-b75f-35e9d568d97a.png)
(WeChat only have QRCode that have to be scanned by phone)

**Comment by klumb** [comment]
Thank you @xiaoya-Esther Xiaoya

After the website migration, I will create a more in-depth participate module for the CHAOSS Chinese community and add these links.

Additionally, I will be adding BST to all of the meetings

**Comment by xiaoya-Esther** [comment]
> Thank you @xiaoya-Esther Xiaoya
> 
> After the website migration, I will create a more in-depth participate module for the CHAOSS Chinese community and add these links.
> 
> Additionally, I will be adding BST to all of the meetings

Sure! Thank you @klumb

**Comment by klumb** [comment]
This is resolved.
