### ISSUE TITLE
Change the sponsor prospectus link on CHAOSScon NA 2021 website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#625]
The link currently goes to the github repo. It would be better to directly download the file when someone clicks: 

https://chaoss.github.io/website/CHAOSScon/2021NA/CHAOSSconNA21_funding_prospectus.pdf

**Comment by adithyaakrishna** [comment]
@GeorgLink I couldn't find the exact sponsor section code located in the repo, if you don't mind can you please point me to that? 👀

**Comment by GeorgLink** [comment]
This needs to be changed in Wordpress by an admin. I don't think there is a file in the repo for this.

**Comment by klumb** [comment]
This has been changed on the new site. The old site will be deprecated on July 21st
