### ISSUE TITLE
Add new Evolution Metric "Contribution Attribution"

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#626]
Please add metric release candidate to website.

Comment issue: https://github.com/chaoss/wg-evolution/issues/410

Markdown file: https://github.com/chaoss/wg-evolution/blob/master/focus-areas/community-growth/contribution-attribution.md

Focus Area: Community Growth

**Comment by adithyaakrishna** [comment]
@GeorgLink Could you please let me know where is this supposed to be added? 👀 
Would love to take this up 💯

**Comment by GeorgLink** [comment]
I think this is the file: https://github.com/chaoss/website/blob/master/release/metrics-tables/metrics-evo.md

**Comment by klumb** [comment]
This is resolved
