### ISSUE TITLE
[Bug] - Broken Link at Chaoss Community Software Page

### ISSUE THREAD

**Issue by adithyaakrishna** [chaoss/website#627]
**Description:**
The page, https://chaoss.community/software/#user-content-augur has a broken link 

![image](https://user-images.githubusercontent.com/23498248/124507496-81d1de80-ddeb-11eb-8670-2da5f1bf8dcf.png)

The link is missing a dash here, `https://github.com/chaoss/augur-community reports`

**Expected Behavious:**
The link needs to be changed to https://github.com/chaoss/augur-community-reports 👀

**Comment by adithyaakrishna** [comment]
Would like to work on this! 💯

**Comment by germonprez** [comment]
@sgoggins do you have the working link?

**Comment by adithyaakrishna** [comment]
I have considered The working one as https://github.com/chaoss/augur-community-reports, please do let me know if its the wrong one 😶

**Comment by klumb** [comment]
I think you are correct @adithyaakrishna
