### ISSUE TITLE
Link to Community Handbook is Incorrect

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#642]
In the top navigation bar, the link to the Community Handbook points to this: https://handbook.chaoss.community.

Currently, that redirects to this: https://handbook.chaoss.community/grimoirelab-tutorial/, which is empty

So either we need to change the navigation link to this: https://handbook.chaoss.community/community-handbook/ or we need to change the redirect.

Thanks!

**Comment by GeorgLink** [comment]
Thanks for reporting this!

I introduced the error on the GitBook side. 

It's fixed now.
