### ISSUE TITLE
Broken links in Metrics page

### ISSUE THREAD

**Issue by lucasgonze** [chaoss/website#648]
Open https://chaoss.community/metrics/

Scroll to "Common Metrics Focus Areas"
<img width="355" alt="image" src="https://user-images.githubusercontent.com/111581/131589449-bbbbe972-1735-4553-b5ae-f49deeb77a85.png">

Click on "Contributions" 

Expect: open the page. Actual: nothing happens. 

Diagnosis: the link is `https://chaoss.community/metrics/#user-content-area-focus-area---contributions`, which is incorrect. On inspecting the source, the issue appears to affect some other links as well.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/111581/131589989-8b6ecd82-0323-4009-9090-4e13225cfc43.png">

**Comment by klumb** [comment]
That is a user content header link.

The desired behavior is that it scrolls down the page to the corresponding header.

All of the focus area links are broken. This issue ocurred either right before or as a result of the website migration.

**Comment by lucasgonze** [comment]
Dup

**Comment by GeorgLink** [comment]
Here's the duplicate: https://github.com/chaoss/website/issues/644
