### ISSUE TITLE
Fix DEI metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#652]
DEI metrics don't show on website since the DEI WG renamed the repository and changed the default branch from `master` to `main`.

![Screen Shot 2021-09-09 at 2 14 58 PM](https://user-images.githubusercontent.com/8862021/132748798-4173d16e-4beb-4686-a122-c72ab5df791c.png)

**Comment by germonprez** [comment]
Ah! We were wondering if it would break things. Looks like the answer is 'yes'

**Comment by germonprez** [comment]
@sgoggins you might want to see this.

**Comment by klumb** [comment]
This is resolved for DEI. Please tag me for any other changes to the working group repo structures.

**Comment by GeorgLink** [comment]
Thanks for fixing this so quickly!
