### ISSUE TITLE
URL Mangling on Participate Page

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/website#66]
The Growth Maturity and Decline Bi-Weekly Call workgroup URL is mangled. The link on https://github.com/chaoss/website/blob/master/Participate/growth-maturity-decline-weekly-call.md is correct, but it is not what is being displayed on the website.

**Comment by klumb** [comment]
This appears to be an issue with the GitHub WordPress plugin. I will look into this further and may move the info out of the GitHub module if necessary.

**Comment by klumb** [comment]
@geekygirldawn thanks for spotting this. IT support was able to fix this.

**Comment by GeorgLink** [comment]
Woot woot!
- Thanks for being persistent.

**Comment by geekygirldawn** [comment]
Thank you!!!
