### ISSUE TITLE
Add Mentees from 2021 to website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#660]
We list past Mentees on our website: https://chaoss.community/chaoss-mentorship/

This issue is to add more mentees to this file: 
https://github.com/chaoss/website/blob/master/Community/alumni.md

**[GSOC 2021:](https://github.com/chaoss/community/blob/master/GSoC-interest.md)**
- Yash Prakash
- Ritik Malik
- Dhruv Sachdev
- Anuj Lamoria
- Rasmi K A
- Yeming Gu

**[Summer of Open Source Promotion:](https://github.com/chaoss/community/blob/master/Summer-OSPP-interest.md)** 
- Veerasamy Sevagen

**Comment by tabassum2507** [comment]
Would love to work on it!

**Comment by GeorgLink** [comment]
Thanks @tabassum2507 , your contributions would be very welcome! 

What questions do you have to get started on this?

**Comment by prsndp** [comment]
> Thanks @tabassum2507 , your contributions would be very welcome!
> 
> What questions do you have to get started on this?

@GeorgLink hi, Am adding these '21 mentees in almuni.md file but here the problem is how to find their mentors and projects as the past list.

**Comment by GeorgLink** [comment]
Please let me know if you need anything else for this.

**Comment by Rottenblasters** [comment]
@GeorgLink  I have completed working on this issue the link to the PR is [here](https://github.com/chaoss/website/pull/694) please review the request
