### ISSUE TITLE
Adding Newcomer Form for Onboarding

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#676]
Hi @klumb! 
In the DEI Working Group, we have been discussing streamlining and improving the onboarding experience for newcomers. An idea was posed that we develop an intake form on the site, for people to have a direct way to reach out, and register their interest in participating in the community.

[Here is the form](https://docs.google.com/forms/d/e/1FAIpQLSd2-JGEYYLl9ZOgpPxL7ihvW-9kvzfTxgIpuyXfxLizbyIi1A/viewform?usp=sf_link). We'd like to keep it as a Google Form and just link to it somewhere. 

Could you add it where it makes the most sense? Maybe participate page? Front page with a "Get Involved" button or something?

What would you recommend?

**Comment by ElizabethN** [comment]
We will collect it in a spreadsheet that will be under the CHAOSS gmail account. I will be the one to respond to those who are submitting the form. 

Also, this is not urgent to add to the website just as a point of note. We are going to promote the form through other means first (twitter, newsletter, mailing list).

**Comment by klumb** [comment]
This should be included in the upcoming website redesign.

**Comment by ElizabethN** [comment]
I think this is no longer relevant to our newcomer workflow, so I'm going to close this issue.
