### ISSUE TITLE
Join Us Button

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#691]
Hi @klumb 

We would like to rename the "Learn More" button that points to the About. Instead, we would like to rename the button on "Join Us" or something like that that points to Matt C's Where Do I Start blog post: 

https://chaoss.community/blog-post/2021/10/13/learn-more/

Ultimately, we'd like to have two buttons - one that helps people who want to contribute and one that helps people who want to use the metrics and software. 

Do you have thoughts on doing this?

**Comment by klumb** [comment]
This sounds good, I will take a look and give this some thought.

**Comment by germonprez** [comment]
Hi @klumb have you had a chance to reflect on this?

**Comment by klumb** [comment]
@germonprez In regards to first part, I renamed the button and pointed it at the blog.

I think that blog should be turned into a static web page and added to the navigation. 

In regards to the other button, we don't have a place to point it yet. But I envision that being a page that provides links to the models, software usage pages, and badging. I think that is something to work on this year.

both of these buttons should be in the navigation and not just call-out buttons.
