### ISSUE TITLE
Update Governing Board website

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#693]
Move to Former Governing Board members:

- [ ] Andrea Gallo ([record](https://lists.linuxfoundation.org/pipermail/chaoss-members/2021-October/000329.html))
- [ ] Ray Paik ([record](https://lists.linuxfoundation.org/pipermail/chaoss-members/2021-November/000343.html))

Add new Governing Board members ([record](https://lists.linuxfoundation.org/pipermail/chaoss-members/2021-November/000355.html)):

- [ ] Sophia Vargas
- [ ] Yehui Wang

I asked the new board members for a picture and bio and will share them here.

**Comment by Rottenblasters** [comment]
@GeorgLink , I would like to work on this issue

**Comment by germonprez** [comment]
Thanks for your interest @Rottenblasters 

@GeorgLink do you have pix?

**Comment by germonprez** [comment]
Actually, this has been completed: 
https://chaoss.community/about/governing-board/ 

I'm going to close this issue but @Rottenblasters if there are other things you'd like to help with, that would be great!! 

Also pinging @ElizabethN -- CHAOSS community manager who can help too.

**Comment by Rottenblasters** [comment]
@germonprez , thanks for letting me know, I have actually submitted a [PR](https://github.com/chaoss/website/pull/694) for the [issue](https://github.com/chaoss/website/issues/660), waiting for it to get reviewed.

**Comment by klumb** [comment]
I went radio silent for a couple of weeks around the holidays in November so I was unaware that this issue was created. This task was completed independently a couple of weeks ago following a community call.
