### ISSUE TITLE
Blog Post was Merged but Didn't Get Published

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#698]
Hi @klumb! Before the break, I tried merging [this blog post](https://github.com/chaoss/website/pull/687) written by @Anita-ihuman but it never showed up on the site, as far as I can tell. Would you be able to troubleshoot? If we can't figure out what happened, I can manually publish it - just let me know.

Thank you! :pray:

**Comment by klumb** [comment]
Sorry, I was taking a break from CHAOSS when this was done.

There is no automatic posting of blogs from GitHub. After the blog is merged, the post has to be created on WordPress. This includes adding meta information and the Github address of the post. It only takes a second, I can show you the process if you would like.

I made a few edits and published it on the site.

However, there is an issue with the size of the image. @Anita-ihuman or @ElizabethN, could you change the image size. The image is blurry. The best way to fix it would be to make the image smaller. I suggest cutting the width and height of the image in half.

**Comment by ElizabethN** [comment]
@klumb I see the draft ready to be published and I think @Anita-ihuman changed the size of the image, but it isn't showing up in the post. Is this something we have to force from GitHub? Is there something I can do to move this forward? Happy to help!
