### ISSUE TITLE
Add CHAOSS "O" to media page

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#704]
Hi @klumb! We were hoping to add this to our media page, based on branding conversations with @germonprez and @uoduckswtd1.

The file can be found here: https://github.com/badging/meta/tree/master/assets/chaoss.

Thank you! Let us know if you have any questions.

**Comment by TejasMate** [comment]
This issue is solved by @Raeskaa, so close this issue @klumb @GeorgLink

**Comment by GeorgLink** [comment]
Thanks!
