### ISSUE TITLE
GSOC Micro-tasks and questions

### ISSUE THREAD

**Issue by klumb** [chaoss/website#708]
### Idea: Build Knowledgebase Application on CHAOSS Website

Hours: 350

Micro-tasks and place for questions: https://github.com/chaoss/website/issues/708

While much of the work of CHAOSS is done in GitHub, the CHAOSS website is often the first place people visit to get information https://chaoss.community/. The goal of the website is to create clear paths for new members who want to contribute, metrics users who want information about metrics, and existing members who need information about project operations. As project grows, there is a need for alternative display and categorization options for knowledgebase topics to reduce the burden on website visitors in finding the information that they need.

Work on this project would require the student to work closely with the mentors and the community to come up with different display and categorization options for CHAOSS Knowledge Base topics. CHAOSS knowledgebase topics that are currently under consideration for this application are released metrics, metrics models, and contributor handbook information. Information about these topics are captured and stored in GitHub repositories by the relevant working groups. The application will need to pull information from github markdown documents to display on the website knowledge base application (we have existing code that does this).

**The aims of the project are as follows:**

    Use Wordpress to implement a knowledge application (example knowledgebase plugin up for consideration - https://wordpress.org/plugins/basepress/). 
    Research and ideate different display options and categorizations for knowledgebase topics.
    Build web pages to display different knowledgebase topics.

The aims will require working with front-end web development technologies and WordPress to build a knowledgebase application that can display information about knowledgebase topics.

    Difficulty: Low
    Requirements: Interest in front-end web development
    Recommended: Experience with Wordpress, HTML, CSS, JavaScript, and GitHub Markdown
    Mentors: Kevin Lumbard, Matt Germonprez, and Elizabeth Barron

**Comment by klumb** [comment]
### Micro-Tasks:

**Comment by yash2002109** [comment]
Hi @klumb, 

I would like to work on this project as a student for GSoC'22.

**Comment by yaodada123** [comment]
Basically, wordpress is a way to build web pages for visitors to browse and implement two knowledge base plugins to facilitate theme switching, right?

**Comment by klumb** [comment]
@yaodada123 

The CHAOSS website is built using WordPress. This project will likely involve selecting a knowledgebase plugin and implementing it on the website. This may also involve some light HTML, CSS, Javascript, or Database work. 

WordPress is an open source content management system (CMS) written in PHP and paired with a database. Features include a plugin architecture and a template system.

Word press offers some free templates and hosting options if you want to practice using the technology.

**Comment by yaodada123** [comment]
@klumb  
That sounds good,I think I will try it.
Now I am familiar with HTML, CSS and JS. In fact, I don't know much about wordpress. I have only used it for my personal blog site and deployed it to cloud services.What else do you think I need to know specifically?And could you please tell me what is expected of us?

**Comment by klumb** [comment]
Sharing info from private email exchange - 

The general workdpress theme template we use is: 
Salient Version: 12.1.5

By [ThemeNectar](https://themeforest.net/user/themenectar)

Then we use a modified child theme to get to some of the CHAOSS specific design choices.

We don’t use a plugin to pull text from GitHub, we have some code that was written for us to pull the content from Github. You would have access to the site and this code if you get selected. Documents from Git is a plugin that provides similar functionality. It doesn’t quite work the same way our code works but I have considered it in the past as a possible replacement should our code fail. It would work for a prototype if you want to incorporate it however it is not necessary. 

You don’t need to pull actual content or make your website look like the Chaoss site. 

The design of the website will actually be changing over the summer, so you have some liberty in the designs that you choose. My only request is that you use The CHAOSS colors and Font style - which you should be able to pull from inspection. 

...And you can just populate the knowledge base areas with lorem ipsum.

**Comment by klumb** [comment]
Sharing info from private email exchange - 

The knowledge base is an attempt to provide one place for new users to get information without them having to go to various GitHub repos or other platforms.

The topics I would like to see right now would be metrics, metrics models, and community handbook information.

The metrics info exists and should be pretty easy to incorporate. 

The metrics models are in the early stage so no documents exist yet.

The community handbook exists but we are in process of cleaning it up. This may involve improvements to both structure and content. If you have a structure or organization that you think will work, include it in your prototypes. You have some leeway to tell us what you think these should look like. Don’t let our existing organization limit you. 

I think the organization and structure are the interesting parts of this proposal - not the content of those focus areas.

**Comment by Saurabh-Suchak** [comment]
Hey @klumb I would like to work on this project for GSoC ' 22.

**Comment by BELAOURASARA** [comment]
Hello @klumb , 
I'm very interested in working on this project during GSOC 2022 !

**Comment by klumb** [comment]
Welcome @BELAOURASARA

**Comment by himanshu007-creator** [comment]
Hi! @klumb , 
i am really interested to wortk on this project during GSOC' 22

**Comment by klumb** [comment]
Welcome @himanshu007-creator

**Comment by Akshaya101** [comment]
Hello @klumb I'm a GSoC'22 participant and I'm interested in working on this issue

**Comment by klumb** [comment]
Welcome @akshaya101

**Comment by klumb** [comment]
Hi all, 

How are the micortasks coming along?

Please let me know if you have questions or would like chat about this project. I could set up a zoom meeting.

**Comment by yash2002109** [comment]
Hi @klumb,

The tasks have been coming along nicely. I have started working on the proposal too, I'll soon give you a detailed update!

I would really like to talk more about the project over a zoom meeting. Perhaps you could schedule a meeting next week and the interested contributors could join in?

**Comment by klumb** [comment]
Thanks @yash2002109.  

Hey all, would 9 am US Central time work?

**Comment by yash2002109** [comment]
@klumb, could you specify the date?

**Comment by klumb** [comment]
I can do this any day next week.

Feel free to shout out a day that works for you all.

**Comment by BELAOURASARA** [comment]
> Thanks @yash2002109.  
> 
> Hey all, would 9 am US Central time work? 

It works for me !

**Comment by BELAOURASARA** [comment]
@klumb 
I've looked for Salient 12.1.5 theme on the web and I didn't find it ( I've found +13.0 versions only). Could you please share with us the link where we can download it ?

**Comment by Akshaya101** [comment]
@klumb 
11th April, US Central time work, IST (7:30pm)
Is this okay with everybody?

**Comment by klumb** [comment]
@BELAOURASARA  **do not** use the salient theme in your prototypes. This theme has a license fee.  

I am sharing the link to the theme we use so you can see the demo and find info about it for design purposes. 

https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266

You should find a free theme or style your prototype yourself. Your prototypes don't have to look exactly like our website.

**Comment by klumb** [comment]
Thanks @Akshaya101 

I am checking with @ElizabethN to see if she is free on Monday, Wednesday, or Thursday at 9am US Central. if so, I will send out a calendar invite.

**Comment by klumb** [comment]
Okay everyone we are scheduled.

GSOC Knowledgebase project meeting
Scheduled: Apr 11, 2022 at 9:00 AM to 10:00 AM US Central time
Location: https://zoom.us/my/chaoss

You can grab the calender event from https://chaoss.community/participate/

**Comment by klumb** [comment]
This session will be an opportunity to ask questions about the Knowledgebase project. I don't have anything specific planned.

**Comment by HerambLimaye** [comment]
hey @klumb actually wordpress free is not allowing me to use Wordpress plugins, so any alternative.
You will find below attached screenshot related to issue
![Screenshot (951)](https://user-images.githubusercontent.com/69971489/163454838-e8155036-b465-4ab1-8b29-ccafb9a0c800.png)

**Comment by klumb** [comment]
Hi, @HerambLimaye I haven't encountered this issue before.

Let do some checking.

Has anyone else had problems with this?

**Comment by HerambLimaye** [comment]
Thanks @klumb, anyone else who knows what I am doing wrong or knows any alternative please fill free to let me know

**Comment by HerambLimaye** [comment]
[https://wordpress.com/start/plans](https://wordpress.com/start/plans) this was the link

**Comment by klumb** [comment]
I wasn't aware the plugins aren't allowed in the free version. @channel if there is a way around this, please share.

For your prototypes, you can create the models using other tools if you need to. Just make sure you are researching available knowledge base plugins for WordPress and modeling their structure into your prototype.

**Comment by Akshaya101** [comment]
To work on locally and establish the microtasks I used [wordpress.org](https://wordpress.org/) . This lets you to establish Wordpress locally and you can also use plugins on it. It does not provide hosting though.

**Comment by klumb** [comment]
Perfect! Thanks @Akshaya101

**Comment by HerambLimaye** [comment]
Thanks @Akshaya101 downloading it now

**Comment by yash2002109** [comment]
Hi @Akshaya101 & @HerambLimaye,

You also checkout this video: https://youtu.be/OuqOUgn2lxg

This provides you complete access to WordPress alongwith hosting on a free domain!

**Comment by arneja-arnav** [comment]
Hi @klumb @yash2002109 ,
So nice to meet you guys! We interacted on the IRC channel before but I don't think I introduced myself well. I would love to work on this project as well. Can my proposals still be reviewed?

**Comment by AmaanSayyad** [comment]
Hi @klumb,
Hope you doing well.

I would like to work on this project.

**Comment by klumb** [comment]
Welcome @AmaanSayyad 

The deadline for submission is April 19, 2022 13:00 US Central Time (UTC-5).

**Comment by klumb** [comment]
Thank you all for the submissions. We got seven submissions for this project. Best of luck to all of you.
