### ISSUE TITLE
Prefered way of submitting images for blog posts?

### ISSUE THREAD

**Issue by jgbarah** [chaoss/website#71]
When uploading a blog post, I tried to figure out the best way of including some images (JPGs, PNGs...). Should I upload them to the same directory where the blog posts are submitted, or somewhere else? (I mean, in some subdirectory or something...)

**Comment by klumb** [comment]
Currently we are just uploading them to the same directory (please add some directions in the comments on how you would like them used). We may need to streamline this process further if we are increasing our blog activity.

Sincerely, 


Kevin Lumbard
University of Nebraska at Omaha
PKI 367

**Comment by jgbarah** [comment]
OK. Thanks a lot!
