### ISSUE TITLE
Issue templates now use Issue forms instead of markdown

### ISSUE THREAD

**Issue by Ayush7614** [chaoss/website#710]
Markdown templates often made it difficult to capture the whole context, by expecting the contributors to read the markup, uncomment lines and delete relevant context.

Issue forms beta was released for public repositories last month, as mentioned by GitHub on this [blog](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). We would like to migrate the issue templates to YAML-based forms which are easy to fill up and maintain, helping us capture relevant context.

There is no issue templates in the project so i would like to work on the issue

**Comment by Ayush7614** [comment]
@klumb please assign me this issue

**Comment by klumb** [comment]
@Ayush7614 Issue/pr forms is something we are discussing across the project. This work will likely be done out of the CHAOSS Common working group. If you are interested in working on this please reach out to that group on the Slack channel attend the upcoming Zoom meeting.

Details are here: https://chaoss.community/participate/
