### ISSUE TITLE
Update Banner on Home Page

### ISSUE THREAD

**Issue by yash2002109** [chaoss/website#712]
CHAOSScon was held in 2021. The banner on the homepage can be updated with a more recent announcement!
![image](https://user-images.githubusercontent.com/77677278/158378276-cfbed42f-3fc7-449e-8687-984c09b23cfe.png)

Suggestion: Perhaps we could replace the text and add that CHAOSS will be participating for GSoC, GSoD and Outreachy

**Comment by germonprez** [comment]
@klumb how easy is it to change the text on this image?

**Comment by klumb** [comment]
Good idea @yash2002109 

@germonprez This is very easy to change

**Comment by klumb** [comment]
I updated this based on your reccomendation. Thanks

**Comment by yash2002109** [comment]
Hi @klumb,

Since the GSoC application deadline has already passed, should we could consider removing that and adding an **announcement for CHAOSScon 2022** like it was previously?

**Comment by klumb** [comment]
maybe just remove altogether as it may not make it through the redesign
