### ISSUE TITLE
404 error on 

### ISSUE THREAD

**Issue by camillem** [chaoss/website#717]
Hi, 
I had bookmarked  the URL https://chaoss.community/metric-bus-factor/ and I now get a 404 error.
The page https://chaoss.community/metrics/ still lists this same link for the bus factor.
Tested  in Firefox 99.0 and Chromium Version 100.0.4896.88 (Build officiel) snap (64 bits)

Thanks,
Camille

![BusFactor404_Firefox](https://user-images.githubusercontent.com/438000/163454199-93f77044-bcb7-4149-bdeb-efcbed0f2f34.png)
![BusFactor404_Chromium](https://user-images.githubusercontent.com/438000/163454244-3a040ce1-584d-46b6-b6b4-4b976107f386.png)

**Comment by klumb** [comment]
Thanks, @camille

I was able to replicate this and track down the issue. It should be good now. 

Please close the issue if it is now resolved for you.

**Comment by camillem** [comment]
@klumb It is resolved for me also. Thanks very much.
