### ISSUE TITLE
Module for Youtube Playlist on CHAOSSconNA18 page

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#72]
Please create a module on the CHAOSScon website for this the YouTube playlist.

https://www.youtube.com/playlist?list=PL60k37cxI-HRgI3MUFtQMntyW8P4ufzbg

The videos have audio only on the left channel, but that does not affect this issue, because we can change the videos in the playlist any time.

**Comment by klumb** [comment]
done

**Comment by GeorgLink** [comment]
Thanks!
