### ISSUE TITLE
Metrics Release -- April 18, 2022

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#722]
Hi Kevin, 

I just ran through the metrics (Firefox/Mac) that were released. Here were the five things that I saw: 

Not showing: https://chaoss.community/metric-inclusive-experience-at-event/ 

404: https://chaoss.community/metric-conversion-rate/ 

404: https://chaoss.community/metric-cii-best-practices-badge/

Not Showing: https://chaoss.community/metric-project-velocity/

404: https://chaoss.community/metric-contributor-recommendibility/

**Comment by klumb** [comment]
Thanks @germonprez 

1. The name for inclusive experience at event was incorrect in the link. (resolved)
2. Conversion rate was removed from the release so it should be 404. It looks like my last edits didn't get pushed. I may have forgotten to save. The table link was not removed (resolved)
3. CII best was changed to ossf best. Same issue as 2. This changed everywhere except the table (resolved)
4. The name for project velocity was incorrect in the link. (resolved)
5. The name for project recommendability was incorrect in the link (resolved)

Also removed project popularity from the release. Same issue as 2 and 3. 

Please confirm and close.

**Comment by germonprez** [comment]
All good. Thanks!
