### ISSUE TITLE
CHAOSS Board for Metrics Release 

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#723]
Hi Kevin, 

The CHAOSS Board is now: 

Yehui Wang, Huewei 
Sophia Vargas, Google 
Amy Marrich, Red Hat
Armstrong Foundjem, MCIS Laboratory at Queen's University
Daniel Izquierdo, Bitergia
Dawn Foster, VMware
Don Marti, CafeMedia
Georg Link, Bitergia
Ildikó Vancsa, OpenStack
Kate Stewart, Linux Foundation
Matt Germonprez, University of Nebraska at Omaha
Nicole Huesman, Intel
Sean Goggins, University of Missouri
Wayne Beaton, Eclipse Foundation

Remove Ray Paik
Remove Andrea Gallo
Add Yehui Wang
Add Sophia Vargas

**Comment by klumb** [comment]
resolved
