### ISSUE TITLE
Incorrect HTML rendering between bullet and sub bullet points

### ISSUE THREAD

**Issue by TejasMate** [chaoss/website#729]
Issue: Adds blank line between **Bullet Heading** end with **fullstop(.)** and **Question Mark(?)** and **Sub bullet's points** 

I guessed there is a bug in code of extracting markdown files or converting into web format. 

Check Comparison:
Eg: https://chaoss.community/metric-diversity-access-tickets/
Markdown: https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/diversity-access-tickets.md

Eg: https://chaoss.community/metric-code-of-conduct-at-event/
Markdown: https://github.com/chaoss/wg-dei/edit/main/focus-areas/event-diversity/event-code-of-conduct.md

**Comment by klumb** [comment]
I have edited these individual metrics and made a proposed change to the metric template to resolve this issue.

Leaving this open to investigate if there is anything we can do to edit our GitHub plugin code.
