### ISSUE TITLE
Create CHAOSSCon EU 2019 Page

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/website#73]
Opening this as an issue to give @klumb one place to track this, instead of digging through email threads :)

About section - same as 2018 NA.

Where - Brussels, TBD.

When - Friday, February 1, 2019 from 10:00am - 5:00pm (we can adjust the times later if we need to)

Organizing Committee: (the people who have already chimed in here - we can add more people later)
Georg Link, University of Nebraska at Omaha
Dawn Foster, The Scale Factory
Nicole Huesman, Intel
Daniel Izquierdo, Bitergia
Jesus M. Gonzalez-Barahona, Rey Juan Carlos University / Bitergia
Kevin Lumbard, University of Nebraska at Omaha (assuming you are OK with this) :)

Call for Participation Section - use the [NA content from this commit](https://github.com/chaoss/website/commit/2e96db2d23296708a6d9df73afd234017a0183b2#diff-409f9c3af9b267a1af5b3e8c6222662d) as a template. I'm happy to update the dates and link after the page is up.

Schedule - TBD

**Comment by klumb** [comment]
I have created a an 2019EU folder to create the content for the site.

**Comment by GeorgLink** [comment]
I think this is complete.
