### ISSUE TITLE
Repository cleanup

### ISSUE THREAD

**Issue by TejasMate** [chaoss/website#730]
Lots of directories/files are irrelevant, either moved to WordPress or old GSoC files

Here is a list of directories and files that are not necessarily relevant. Remove them after discussion
~~1. [GSoC-Artifacts directory](https://github.com/chaoss/website/tree/main/GSoC-Artifacts)~~
2. [Home directory](https://github.com/chaoss/website/tree/main/Home)
3. [Images Directory](https://github.com/chaoss/website/tree/main/Images)
 Please suggest more dir./files to be removed

**Comment by yash2002109** [comment]
Hi @TejasMate,

The GSoC artifacts directory was removed in #727. I do not think the `Home` directory can be removed since it provides for the content on the homepage.

**Comment by yash2002109** [comment]
I think that's a good idea @klumb!

**Comment by TejasMate** [comment]
I think 

> Hi @TejasMate,
> 
> The GSoC artifacts directory was removed in #727. I do not think the `Home` directory can be removed since it provides for the content on the homepage.

Thanks Buddy

**Comment by ElizabethN** [comment]
We have done a website cleanup since this issue was opened, so I think it's no longer relevant. Thanks @TejasMate and @yash-yp for working on this!
