### ISSUE TITLE
Add DEI Badge to the CHAOSScon website

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#743]
Hi @klumb! 

I'm not sure where we'd add this badge, or if it would be weird to display our own badge on the CHAOSScon website, but here is the link to the generated markdown. We could put this on the event details page or somewhere else, if you think it fits better somewhere else.

`![Assigned badge: gold](https://img.shields.io/badge/D%26I-Gold-yellow?style=flat-square&labelColor=583586&&link=https://github.com/badging/event-diversity-and-inclusion/issues/188/&logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDI1MCAyNTAiPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTcuMSw0OS4zYzE4LTYuNywzNy44LTYuOCw1NS45LTAuMmwxNy41LTMwLjJjLTI5LTEyLjMtNjEuOC0xMi4yLTkwLjgsMC4zTDk3LjEsNDkuM3oiLz4KPHBhdGggZmlsbD0iIzZBQzdCOSIgZD0iTTE5NC42LDMyLjhMMTc3LjIsNjNjMTQuOCwxMi4zLDI0LjcsMjkuNSwyNy45LDQ4LjVoMzQuOUMyMzYuMiw4MC4yLDIxOS45LDUxLjcsMTk0LjYsMzIuOHoiLz4KPHBhdGggZmlsbD0iI0JGOUNDOSIgZD0iTTIwNC45LDEzOS40Yy03LjksNDMuOS00OS45LDczLTkzLjgsNjUuMWMtMTMuOC0yLjUtMjYuOC04LjYtMzcuNS0xNy42bC0yNi44LDIyLjQKCWM0Ni42LDQzLjQsMTE5LjUsNDAuOSwxNjIuOS01LjdjMTYuNS0xNy43LDI3LTQwLjIsMzAuMS02NC4ySDIwNC45eiIvPgo8cGF0aCBmaWxsPSIjRDYxRDVGIiBkPSJNNTUuNiwxNjUuNkMzNS45LDEzMS44LDQzLjMsODguOCw3My4xLDYzLjVMNTUuNywzMy4yQzcuNSw2OS44LTQuMiwxMzcuNCwyOC44LDE4OEw1NS42LDE2NS42eiIvPgo8L3N2Zz4K)`

**Comment by klumb** [comment]
To your comment - I have mentioned several times that I don't think it is appropriate to badge ourselves. I think it undermines the integrity of the process (there is either a conflict of interest or the impression of one). However, my comments on this were completely disregarded. So if you want, I will go ahead and add it. I think event details would be a good place. 

To my comment - I would prefer that we just make a statement that our project adheres to or implements chaoss badging best practices, without actually taking or displaying the badge. 

Let me know what you want me to do.

**Comment by germonprez** [comment]
Hi Kevin, 

I don't believe that your comments were disregarded.

**Comment by klumb** [comment]
I think adding the badge along with a disclaimer that the badge process was done by an independent third party along with a statement about how we strive to adhere to the DEI best practices that we as CHAOSS have defined, would alleviate my concerns.

**Comment by ElizabethN** [comment]
@klumb I think going through the process was important, and it did lead to us making some improvements with regard to the way the information was displayed on the website. It also will lead to improvements for the badging process itself, as we got firsthand experience through an applicant's eyes (more accurately than just submitting test events). I think it was valuable overall, and I'll recommend that we do it again for the next CHAOSScon. 

With that, I *do* understand your concerns with regard to displaying it on the CHAOSScon website, which is why I put this in an issue instead of a PR. I honestly couldn't remember where we landed and what was decided :blush:  I completely support leaving it off the website, or adding the verbiage you mentioned in the future. Considering the event is only a few days away, leaving it off seems the easiest course of action this time around. :+1:

**Comment by klumb** [comment]
@ElizabethN, my view on this was definitely in the minority and that is okay. I only mentioned it because you expressed some concern in your post.

I am very happy to add it or any version of it to the website and I am pretty sure it was decided that we should add it in the community meeting. 

I agree with everything you said about going through the process and how valuable that is.

**Comment by klumb** [comment]
I am going to add it where you suggested.

If we want to add some text to it we can but I will leave that decision up to others.

**Comment by klumb** [comment]
Added to the site
