### ISSUE TITLE
Renaming value wg to ospo

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/website#755]
Github the repo name of value wg is changed to ospo wg. @klumb please update the links.

**Comment by klumb** [comment]
This is done. @vinodkahuja can you keep an eye on it for a day or two in case I missed one of them and website caching is preventing me from seeing it?

**Comment by vinodkahuja** [comment]
@klumb I have found a few places that need to be fixed and created PR # 576 for that.

**Comment by klumb** [comment]
Was this a seperate PR? 
They are fixed now.

**Comment by klumb** [comment]
Cool

**Comment by ElizabethN** [comment]
Closing this issue, as I think it's been taken care of. Thanks @vinodkahuja!
