### ISSUE TITLE
Remove wg timings on participate page

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/website#757]
On the description of each working group on the participate page (https://chaoss.community/participate/) there are meeting timings that do not align with the CHAOSS calendar. For example, OSPO/value time does not align with the calendar. I would propose deleting meeting timings for all wg or referring them to the CHAOSS calendar for meeting times.

**Comment by ElizabethN** [comment]
Hi @vinodkahuja! I think this information shows up a few times in the website, but it's listed in these files https://github.com/chaoss/website/tree/main/Participate. If we keep these updated here, they will update everywhere this github block is called. I will go through and make sure they are all updated, as I know there have been other changes to working groups as well. Thanks for catching this!
