### ISSUE TITLE
Blog Not on Website

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#763]
Hi, 

I think that in the redesign, the blog got lost and isn't in the navigation. I may have missed it too!

**Comment by klumb** [comment]
The page is still live but isn't in the navigation. 
https://chaoss.community/blog/ 

It was never discussed as a required page during planning meetings, and at the time, there was little activity on it, so during the simplification, it was removed from navigation.

If you want it on the navigation, let me know where.

**Comment by germonprez** [comment]
Seems like under 'community' would be the place.

**Comment by klumb** [comment]
Added to the navigation, and the page has been updated.
