### ISSUE TITLE
Update WG Meeting info 

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#777]
We need to double-check that the info in these files is accurate because these files are pulled into the CHAOSS website in a few different places. 

https://github.com/chaoss/website/tree/main/Participate

**Comment by ksba2004** [comment]
I would like to work upon this. Please assign this too me. Also if possible please provide some resources.

**Comment by ElizabethN** [comment]
This information has been moved to [a new document](https://chaoss.community/kb/working-groups/) that will be easier to maintain when working group info changes.
