### ISSUE TITLE
given link is not clickable 

### ISSUE THREAD

**Issue by shubham21155102** [chaoss/website#778]
![image](https://user-images.githubusercontent.com/98862179/212816083-ce9efa06-e0e4-4018-8f5e-69ae336ff52e.png)

**Comment by ElizabethN** [comment]
Hi @shubham21155102! Just to clarify - this is in the website repo readme?

**Comment by shubham21155102** [comment]
Yes this the readme of the repo that is rendering on the production.
Because this repo doesn't contain any index.html file.

**Comment by shubham21155102** [comment]
Yes yes in the readme file

**Comment by ElizabethN** [comment]
Hmm it's clickable for me. What am I missing? 😅

**Comment by klumb** [comment]
Hi all,

That's not a link it is just a URL.

I would guess that either GitHub or your browser is converting it to a link (maybe inconsistently).

If you want it to always be a link, you will need to edit the markdown. I don't think the original intention was to make it a link. I think it was more descriptive in nature.

**Comment by shubham21155102** [comment]
Ya ya alright

**Comment by ElizabethN** [comment]
>I would guess that either GitHub or your browser is converting it to a link (maybe inconsistently).

Neat, thanks GitHub! :smile:
