### ISSUE TITLE
Missing Metric in KB

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#783]
The metric [Defect Resolution Time (AKA Defect Resolution Duration)](https://chaoss.community/metric-defect-resolution-time/) is a released metric that has a legacy page but that didn't make the transition to the new KB list of metrics. I'm gonna flag you @klumb since you are adding permalinks to each metric page - would you mind copying this one over while you're doing that? Thank youuuuu! :pray:

**Comment by ElizabethN** [comment]
It looks like the same thing happened with [Code Changes Commits](https://chaoss.community/metric-code-changes-commits/). This is a metric that is in the old system but didn't make it over to the knowledge base. Thanks @klumb! ✨

**Comment by ElizabethN** [comment]
Here is one more that I don't see in the KB, @klumb: [Change Request Reviews](https://chaoss.community/metric-change-request-reviews/). (I might be missing something?)

**Comment by klumb** [comment]
Thank you for catching these. I hadn't done a census yet, so I am not surprised we are missing some. I don't think you are missing anything.

**Comment by ElizabethN** [comment]
@klumb I'm going to go ahead and close this since I think we have them all now. Feel free to reopen if you're still working on this.
