### ISSUE TITLE
Proper issue issue templates would make it easier for contributors to contribute and be specific like other repositories

### ISSUE THREAD

**Issue by ItsRoy69** [chaoss/website#784]
![214230801-e8ef698e-5805-4160-ab7e-d26877e363ea](https://user-images.githubusercontent.com/78967360/214574949-743e2c28-4993-4b04-81db-8c7e5b7a06ee.png)

**Comment by ItsRoy69** [comment]
I can work on this issue

**Comment by germonprez** [comment]
While I like Issue templates, we have tried to use them in CHAOSS in the past. They weren't used much at all as people just open and explained things in blank issues.

**Comment by ItsRoy69** [comment]
Oh okay okay

**Comment by ElizabethN** [comment]
@ItsRoy69 usually if there is something for a First Time Contributor or newcomer to CHAOSS, we will label an issue "First Timers Only". I think that might be a better way to find something as a newcomer. :blush:
