### ISSUE TITLE
Grammatical errors on website content 

### ISSUE THREAD

**Issue by BhaswatiRoy** [chaoss/website#788]
![image](https://user-images.githubusercontent.com/78029145/215331721-67358673-4709-44c0-9d43-8e82348ca3cb.png)
missing determinants.

![image](https://user-images.githubusercontent.com/78029145/215331799-b2f43f50-b61d-4487-83c9-ab7f2cb811d1.png)
Missing determinants like articles.

![image](https://user-images.githubusercontent.com/78029145/215331984-05247e06-0aea-4ccf-b9fb-5fc0cfddf473.png)
The word "workflow" has an interrupting space.

![image](https://user-images.githubusercontent.com/78029145/215332134-aeb85726-dc34-496f-be37-5d76e9842dbc.png)
The word "website" has an interrupting space.

![image](https://user-images.githubusercontent.com/78029145/215332185-dceb27bf-fe95-4f05-9724-4a956e9d1f91.png)
It should be "metrics" in plural format.

![image](https://user-images.githubusercontent.com/78029145/215332277-f1fb79a9-4942-4c86-8e41-d5ccf1e31de7.png)
The word "consensus-based" is missing a hyphen.

![image](https://user-images.githubusercontent.com/78029145/215332330-a58144c0-b6e5-4110-a25d-e8312c33ae92.png)
Articles are always recommended before starting nouns of sentences. (4x places)

![image](https://user-images.githubusercontent.com/78029145/215332426-506122ef-215f-41dd-a420-ba6f15eb88bf.png)
should be "during which"

![image](https://user-images.githubusercontent.com/78029145/215332460-04a21023-1b4c-4545-bbf4-b7b9435731bb.png)
It should be "of the GB"

![image](https://user-images.githubusercontent.com/78029145/215332520-b9aff729-9d84-43c3-9d04-70edab627f70.png)
We use singular after "that" and plural after "those"

![image](https://user-images.githubusercontent.com/78029145/215332572-b64144cd-1adf-4e53-8b80-db7a5603d3ac.png)
end of listings so it should be "and service marks"

![image](https://user-images.githubusercontent.com/78029145/215332631-d350a777-6a4d-46a9-b36e-66ff06ddfa1e.png)
Hyphens not needed in "code of conduct"

**Comment by BhaswatiRoy** [comment]
I can work on fixing these grammatical issues

**Comment by ElizabethN** [comment]
Hi @BhaswatiRoy and thanks for opening this! I think the charter is one document that we are not able to change without board approval. Are there other grammatical errors in other documents in our knowledgebase or website that could be fixed?

**Comment by BhaswatiRoy** [comment]
There are some punctuation and determinant errors in the Code of Conduct & Data Policies too.
I haven't checked other sections except "About" yet. I will check for other sections too.

**Comment by adiitiii** [comment]
I'd like to do this small contribution of fixing these grammatical issues.

**Comment by BhaswatiRoy** [comment]
Hello @ElizabethN 
I was just checking through other parts of the website and came across these grammatical issues under CHAOSS -> CHAOSS Community Knowledge Base
![image](https://user-images.githubusercontent.com/78029145/217440052-7f518b5d-81e7-4c1b-b65b-f5d8b39961e8.png)

I can work on fixing these

**Comment by ElizabethN** [comment]
Looks like this was fixed so I'm going to close this! Thank youuuu to those who worked on it! :pray:
