### ISSUE TITLE
Redirect for the old Participate page

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/website#789]
This page https://chaoss.community/participate/ was linked to from a bunch of places (repos, etc.) as the way to find meetings, but now it’s a 404. Can we redirect it to the new calendar page, instead? https://chaoss.community/chaoss-calendar/

**Comment by klumb** [comment]
Yes, we can do that. 

@ElizabethN do you want me to do this?

**Comment by ElizabethN** [comment]
That would be great, thank you @klumb!

**Comment by klumb** [comment]
This is done
