### ISSUE TITLE
Merge Wiki with Website?

### ISSUE THREAD

**Issue by klumb** [chaoss/website#8]

**Comment by GeorgLink** [comment]
The WIKI URL is in wide use today. We can copy all the content and keep the website up-to-date, but I would not eliminate the Wiki at this point --- maybe over time, if we consistently have everything in our repositories and website and no one is using the wiki URL anymore.

**Comment by germonprez** [comment]
I agree. Particularly, there are going to be metrics details that are
specific in the wiki

**Comment by GeorgLink** [comment]
I'd be happy to move the upcoming events page from the wiki to the website and only have one place to maintain this: https://wiki.linuxfoundation.org/chaoss/events#upcoming-events

**Comment by klumb** [comment]
Good idea,  I will merge those elements and let you know when you can remove from the wiki.
