### ISSUE TITLE
Add blog post to link to VMware's CHAOSScon blogpost

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#81]
Here is the blog post by VMware about CHAOSScon. Alexandre gave us permission to "share and/or link to it from the chaoss website".

https://blogs.vmware.com/opensource/2018/10/09/chaosscon-2018-reflections/

**Comment by germonprez** [comment]
This is great! Share to the list?

**Comment by GeorgLink** [comment]
Yes.
