### ISSUE TITLE
GH Modules Sometimes Update Automatically, Sometimes They Don't

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#817]
We have noticed in the past that sometimes our WP pages update automatically when the corresponding files are updated on GH, like they should. But sometimes you have to go into WP and manually update the page in order for it to grab the updated GH content. 

I've been curious about this for a while, but today I noticed that when I changed 4 metric files in ONE PR, 3 of those files updated automatically and 1 of them did not 🤯. This is kind of a placeholder for me as I dig a little deeper into this. It's personal now! 😆 💪

**Comment by ElizabethN** [comment]
@klumb do you think this could be caused by a caching setting somewhere in WP?

**Comment by klumb** [comment]
Yes, this is all caching-related. Some of it may be on the website side, and some of it may be on the client side (your browser).

It is working as it is intended at the website level, so I would be leary of changing any settings. 

I would try clearing the cache in your browser first. Especially if you have visited those pages recently. 

If you are in a hurry, you can clear the cache on the website (sometimes you need to do this a couple of times). However, it should appear on the website within in a day or two at the most, without clearing the cache.

**Comment by klumb** [comment]
If you are wondering if it is occurring on your side, try opening it in a different browser (preferably using a privacy mode).

Or you can reach out to someone else and ask them if they can see the change. I have run into several incidents where I can see the change but someone else cannot. That is due to browser caching.

**Comment by ElizabethN** [comment]
I'm just thinking about those visiting the site who wouldn't necessarily think to clear their local cache

**Comment by klumb** [comment]
For time-sensitive things I would always clear the website cache. But I generally do that manually.

**Comment by klumb** [comment]
I think that clearing the cache on the website side will often trigger browser refreshes as well. Sometimes you need to clear it a couple of times to see the change.

**Comment by klumb** [comment]
Do you want to do a quick zoom meeting?

**Comment by klumb** [comment]
On the browser side, the cache is created when they visit the pages. So if they don't visit the site often you shouldn't have to worry about them clearing their cache. And it will clear on its own in time.

**Comment by klumb** [comment]
Checking the cache settings, the crawler runs every two hours. So 2-3 hours is how long a change would likely take if it is not instantaneous.

**Comment by ElizabethN** [comment]
I think this has been fixed by @klumb so I'm going to close this. We can reopen if it happens again.
