### ISSUE TITLE
(much like #818) another reversed alignment metric

### ISSUE THREAD

**Issue by GaryPWhite** [chaoss/website#832]
Hey folks!

I reported in #818 that a particular metric was right-aligned instead of left-aligned. I'm seeing the same thing here: 

https://chaoss.community/kb/metric-osi-approved-licenses/

I understand wordpress admins are the only ones who could address.. thought I'd bring it to the attention of maintainers!
![image](https://github.com/chaoss/website/assets/7660110/c0811c28-be32-48c8-b2be-0b07e3827eb4)

**Comment by GaryPWhite** [comment]
to be clear, I'm writing these issues because I am only seeing it on one page, in private windows, and after clearing caches.

**Comment by germonprez** [comment]
Pinging @klumb and @ElizabethN who can likely help here.

**Comment by ElizabethN** [comment]
I think it's something to do with the automatic translation function messing with the page alignment, because on my screen it displays correctly 🤔 . Could be a caching issue but I'll let @klumb chime in. I think we've seen this happen before but I'm not sure what the trick was to fixing it. 

@GaryPWhite have you used the translate function at the top in the nav bar? Even going from English -> another language -> back to English might have messed it up.

**Comment by klumb** [comment]
Hi @GaryPWhite

Are you located in the States? Or have you been traveling lately? What browser are you using?

I am unable to replicate the issue on my end. However, we have experienced this issue on a couple of occasions. 

@ElizabethN, you are correct in thinking that it is an issue with our translation software. Caching just makes it a little more challenging to diagnose. 

In the past, this has occurred when our translation software needed to be updated. The usual fix is to update the software (Gtranslate),  clear the server-side cache, and ask the reporter to clear their client-side cache.  

I am taking a look now.

**Comment by klumb** [comment]
I was able to replicate this in google chrome when I switched between languages and used google translate.

@GaryPWhite do you use Google translate?

**Comment by klumb** [comment]
Our translation software (Gtranslate) is built on top of Google Translate software. 

I am wondering if there is an odd interaction between our translation software and Google Translate in Chrome.

Google Translate was updated about 7 days ago so Gtranslate may be pushing an update soon.

**Comment by GaryPWhite** [comment]
> @GaryPWhite have you used the translate function at the top in the nav bar? Even going from English -> another language -> back to English might have messed it up.


Nope, no translation. I can open this in a private window, cleared cache, still seeing. Weird that this doesn't happen on _every_ page.

> Are you located in the States? Or have you been traveling lately? What browser are you using?

Yes, no, firefox. I've reproduced this (typical, broken on my machine syndrome :) ) on safari / chrome / ff for the pages reported though.

Seems like the gtranslate issue might show up server-side for me for some reason? I have been viewing metrics by the 10's recently so it may very well be a "load enough pages" issue.

**Comment by ElizabethN** [comment]
@GaryPWhite is this issue still happening for you? We are purging the cache now (I think?) so hopefully it has been resolved. But let us know if this is something we should be working on. Thanks! 

cc @peculiaruc

**Comment by ElizabethN** [comment]
I'm going to go ahead and close this because I think it's been resolved :+1:
