### ISSUE TITLE
Best way to cite CHAOSS for an academic article? 

### ISSUE THREAD

**Issue by yochannah** [chaoss/website#833]
Hey folks! 

What's your preferred way to be cited in an academic article? Perhaps linking metric releases on Zenodo? 

I'll be taking my best guess for now, but if you share a preferrred way before the 30th (that's, ah, my thesis submission deadline), I'll try to update it :) - and if you're curious, you can find a summary of what I've been doing here:  https://sustainable-open-science-and-software.github.io/

**Comment by germonprez** [comment]
Thanks for the question @yochannah! I don't think we've ever really addressed this. We have references for metrics but not the project itself. If I had to take a guess: 

CHAOSS. (2023). https://chaoss.community/

**Comment by yochannah** [comment]
thanks! :)
