### ISSUE TITLE
Update Board of Directors Page

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#836]
This is a reminder for me and/or the website team to update the Board of Directors page with the changing Board members.

New Board members:
- Anita Ihuman
- Ruth Ikegah
- Brian Proffitt
- Kevin Lumbard

Outgoing members:
- Daniel Izquierdo
- Don Marti

**Comment by germonprez** [comment]
@klumb -- is this something you could do? Would you like me to help by assembling information and pictures?

**Comment by klumb** [comment]
Yes, I can do that. Help would be appreciated. 
We will need a short bio and picture for each.

**Comment by germonprez** [comment]
Will do. I'll track these down and share them with you.

**Comment by geekygirldawn** [comment]
I wanted to just check in this to see if there is anything else you need to get this done? I'm happy to help track down the details if needed :)

**Comment by dicortazar** [comment]
Hello there! I was warned that I was not anymore part of the board given this commit, but I think this decision was not finally taken, and even more recorded and approved. 

During the last board meeting I mentioned that I was happy to step down if there was not space for new members. However, during the election process,  it was decided that we could grow the number of board members over a certain number so we could have space for everyone that applied for this.

In my personal case, I assumed that there was no need to step down as we were growing the final number of board members :).

I guess CHAOSS should have a process to officially add and remove board members, have an official  notification, and I would even say enforce a healthy turnover at some point, but these are topics to cover in  another ticket.

**Comment by geekygirldawn** [comment]
@klumb

**Comment by geekygirldawn** [comment]
@klumb - can you put Daniel back on the board page? @sgoggins - in the future, we need to be really clear about when someone is stepping down from the board and require a yes / no, rather than what we did last time, which was way too ambiguous :)

**Comment by CodeLeom** [comment]
@ElizabethN has this issue been assigned or worked on? I would like to work on this issue

**Comment by klumb** [comment]
@geekygirldawn the change was made on the website. I keep all all the former board members in there. It is just a matter of flipping the switch between former board member and board member. Daniel is back on the website.

@dicortazar, I was sad when I heard you were leaving the board so I am very happy to hear you are staying on.  

I am closing this ticket.

**Comment by dicortazar** [comment]
Thanks @klumb , really appreciated! :)
