### ISSUE TITLE
Making our website more representative of our global community

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#837]
I don't feel like the website accurately represents our global community, generally speaking. 

- We have great photos from past events that could be showcased more on our website, either on the Community home page or the About page. 
- We could create a map of the countries where our CHAOTICS live and work
- We could surface our Chapters a little more, as they are buried underneath a few clicks

@peculiaruc do you think there's someone that would want to work on this? I would love to if no one else wants to take it!

**Comment by peculiaruc** [comment]
> I don't feel like the website accurately represents our global community, generally speaking. 
> 
> - We have great photos from past events that could be showcased more on our website, either on the Community home page or the About page. 
> - We could create a map of the countries where our CHAOTICS live and work
> - We could surface our Chapters a little more, as they are buried underneath a few clicks
> 
> @peculiaruc do you think there's someone that would want to work on this? I would love to if no one else wants to take it!


I had ask around first and revert.

**Comment by peculiaruc** [comment]
> I don't feel like the website accurately represents our global community, generally speaking.
> 
> * We have great photos from past events that could be showcased more on our website, either on the Community home page or the About page.
> * We could create a map of the countries where our CHAOTICS live and work
> * We could surface our Chapters a little more, as they are buried underneath a few clicks
> 
> @peculiaruc do you think there's someone that would want to work on this? I would love to if no one else wants to take it!

@ElizabethN I am assigning this issue to you. Thanks a lot

**Comment by kaxada** [comment]
I am not sure what the technical aspects are involved in coming up with this. The last I heard from @ElizabethN and @klumb is that the main CHAOSS website uses WordPress and you'd need credentials to log in and make changes.  @ElizabethN I think if this is easy to do then we can guide any of the community members willing to contribute. If it is not then you can go on and do it.

**Comment by klumb** [comment]
@kaxada and @ElizabethN 

Getting the content on to the Wordpress site or into Github is not that difficult or technical. Many CHAOSS members have credentials and we are willing to give access to others if they show interest

The barrier for improvements like this is having, locating, or creating the content & artifacts. If the art, images, or documents exist and we know where they are, getting them on the website is easy.

I suggest we start here:

- For the map of where CHAOTICS live,  we ask the design WG or team if they could create that visual for us.
- For images, we ask for a volunteer to collect, sort, and store images in a shared cloud drive. This would involving asking the community to share the images they have. Then we research an image or slideshow application to install on the Wordpress site (ideally the application will pull the images from this shared drive). 

Once we have those two things, building pages around them is much easier.

**Comment by ElizabethN** [comment]
Thanks for your thoughts here @kaxada and @klumb! Greatly appreciated! 

Regarding the photos:
I think we can keep this simple. I have some group photos from the past few CHAOSScons that I can include on the About page. I don't think we need a lot of overhead work on this; mostly I'm just seeking better representation overall, because right now we only have one photo. I am thinking 4 photos max. I think we can periodically update these group shots as we host more events.
In the future, if we do have someone passionate about creating a slideshow, I think it's an excellent way to include community members! 

Regarding the map: 
I think that's an excellent idea @klumb to include the design team. Maybe there are even programs out there that can generate a map from a list of countries in a spreadsheet. We'd just need to compile a list of all the countries where we collectively live. I'll open an issue in the design repo.

Regarding the Chapters:
I'd like to surface these on our About page, at least with the logos and a link to the page that speaks more about them. They aren't mentioned at all on our About page, and this seems like a missed opportunity to showcase them.

**Comment by peculiaruc** [comment]
> Thanks for your thoughts here @kaxada and @klumb! Greatly appreciated!
> 
> Regarding the photos: I think we can keep this simple. I have some group photos from the past few CHAOSScons that I can include on the About page. I don't think we need a lot of overhead work on this; mostly I'm just seeking better representation overall, because right now we only have one photo. I am thinking 4 photos max. I think we can periodically update these group shots as we host more events. In the future, if we do have someone passionate about creating a slideshow, I think it's an excellent way to include community members!
> 
> Regarding the map: I think that's an excellent idea @klumb to include the design team. Maybe there are even programs out there that can generate a map from a list of countries in a spreadsheet. We'd just need to compile a list of all the countries where we collectively live. I'll open an issue in the design repo.
> 
> Regarding the Chapters: I'd like to surface these on our About page, at least with the logos and a link to the page that speaks more about them. They aren't mentioned at all on our About page, and this seems like a missed opportunity to showcase them.

@ElizabethN I see you have a great idea about this issue, I am assigning it back to you. Thank you Elizabeth

**Comment by ElizabethN** [comment]
Closing this for now.

**Comment by peculiaruc** [comment]
Wow! I miss this. So sorry. I will look for someone whenever it is reopened again.
