### ISSUE TITLE
Slack invite link on community page may be expired.

### ISSUE THREAD

**Issue by alice-sowerby** [chaoss/website#886]
It seems as though the Slack invite link on the website has expired. 

I wanted to join the CHAOSS Slack and followed the link given in the page: https://chaoss.community/kb-getting-started/ which points to https://join.slack.com/t/chaoss-workspace/shared_invite/zt-1fah5gu35-5oUQEPT32O2Zt~3MFVNMlw 

This link took me to a login page that was asking for an email address linked to a specific domain. 

Dawn Foster kindly gave me an alternative invite link which worked with my personal email address. I hypothesise that the invite link on the webpage has expired and I was sent to the general CHAOSS signup page which may have restrictions on it.

**Comment by geekygirldawn** [comment]
The link that I gave @alice-sowerby is the one in the footer of the website, so that link still seems to work. I think we just need to update the link in the KB.

**Comment by geekygirldawn** [comment]
@alice-sowerby Thanks for filing the issue!

**Comment by ElizabethN** [comment]
This is fixed! Thank you @alice-sowerby! 😍
