### ISSUE TITLE
Web Page Alignment Problem of Metric 'Upstream Code Dependencies'

### ISSUE THREAD

**Issue by dune0310421** [chaoss/website#893]
The web page of metric ['Upstream Code Dependencies' ](https://chaoss.community/kb/metric-upstream-code-dependencies/) is right-aligned, as shown in the following picture.
<img width="1427" alt="image" src="https://github.com/chaoss/website/assets/94817721/2d64209c-b835-4807-8854-800f1b6a0854">
But all the other web pages are left-aligned.
<img width="1427" alt="image" src="https://github.com/chaoss/website/assets/94817721/939a7d2d-ccb7-484c-b0e0-0c9a61c0410d">

 I think this is an issue with the website layout rather than the content of the metric itself.

**Comment by ElizabethN** [comment]
@dune0310421 apologies for the ridiculously lonnnnng delay here! I think this happens from time to time with the website translation plugin. Usually if this happens, you can clear your cache to keep it from happening again. Thanks and let us know if that doesn't fix it! It looks ok from my end but there might be something else going on.
