### ISSUE TITLE
Old blog post disappeard: Installing GrimoireLab

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#900]
We used to have a blog post: https://chaoss.community/blog-post/2019/10/08/simplifying-how-to-install-grimoirelab/

I think it is now supposed to be available at: https://chaoss.community/simplifying-how-to-install-grimoirelab/

🐞 However, the page is empty. 

The original source is still available in GitHub: https://github.com/chaoss/website/blob/main/archive/Community/News/20191007-install-grimoirelab.md

PS: I'm considering to retire the blog post and re-publishing it with an updated version.

**Comment by ElizabethN** [comment]
I fixed the path to the GH content @GeorgLink and added a redirect :+1: The images are still broken, but I wasn’t sure if you wanted to update any of them (since you’re considering a refresh). Happy to fix the links to them in the meantime if you’d like- just let me know.

**Comment by ElizabethN** [comment]
Going to close this for now - pending the links to the images.

**Comment by GeorgLink** [comment]
If it’s not too much work, let’s fix the images.

A refresh would take the form of a new blog post.

Thanks,
Georg
