### ISSUE TITLE
Proposal: Community page to show only teaser for blog posts

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/website#96]
We have very long blog posts. We would have a better overview of all topics on the community page if we restricted display to a short teaser, maybe first 100 words or so.

**Comment by klumb** [comment]
@GeorgLink , please review.

I think we will want to add dates to the headers.

**Comment by GeorgLink** [comment]
> In regards to the lack of teaser, that was the first one we are pulling directly from github markdown file. I may be able to add the teaser in separately.

That's interesting. 👍

**Comment by GeorgLink** [comment]
> Not sure, I am using the default style. We can try a couple different styles.

Can't hurt, if you have the time.

**Comment by klumb** [comment]
This is done.
